/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    [JsonSubtypes.KnownSubType(typeof(CodeInterpreterTool), "code_interpreter")]
    [JsonSubtypes.KnownSubType(typeof(DocumentLibraryTool), "document_library")]
    [JsonSubtypes.KnownSubType(typeof(FunctionTool), "function")]
    [JsonSubtypes.KnownSubType(typeof(ImageGenerationTool), "image_generation")]
    [JsonSubtypes.KnownSubType(typeof(WebSearchTool), "web_search")]
    [JsonSubtypes.KnownSubType(typeof(WebSearchPremiumTool), "web_search_premium")]
    public partial class AgentToolsInner 
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum FunctionEnum for function
            /// </summary>
            [EnumMember(Value = "function")]
            FunctionEnum = 1,
            
            /// <summary>
            /// Enum WebSearchEnum for web_search
            /// </summary>
            [EnumMember(Value = "web_search")]
            WebSearchEnum = 2,
            
            /// <summary>
            /// Enum WebSearchPremiumEnum for web_search_premium
            /// </summary>
            [EnumMember(Value = "web_search_premium")]
            WebSearchPremiumEnum = 3,
            
            /// <summary>
            /// Enum CodeInterpreterEnum for code_interpreter
            /// </summary>
            [EnumMember(Value = "code_interpreter")]
            CodeInterpreterEnum = 4,
            
            /// <summary>
            /// Enum ImageGenerationEnum for image_generation
            /// </summary>
            [EnumMember(Value = "image_generation")]
            ImageGenerationEnum = 5,
            
            /// <summary>
            /// Enum DocumentLibraryEnum for document_library
            /// </summary>
            [EnumMember(Value = "document_library")]
            DocumentLibraryEnum = 6
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; } = TypeEnum.FunctionEnum;

        /// <summary>
        /// Gets or Sets Function
        /// </summary>
        [Required]
        [DataMember(Name="function", EmitDefaultValue=false)]
        public Function Function { get; set; }

        /// <summary>
        /// Ids of the library in which to search.
        /// </summary>
        /// <value>Ids of the library in which to search.</value>
        [Required]
        [DataMember(Name="library_ids", EmitDefaultValue=false)]
        public List<string> LibraryIds { get; set; }

    }
}
