/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AgentHandoffDoneEvent 
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum AgentHandoffDoneEnum for agent.handoff.done
            /// </summary>
            [EnumMember(Value = "agent.handoff.done")]
            AgentHandoffDoneEnum = 1
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; } = TypeEnum.AgentHandoffDoneEnum;

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public DateTimeOffset? CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets OutputIndex
        /// </summary>
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int? OutputIndex { get; set; } = 0;

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets NextAgentId
        /// </summary>
        [Required]
        [DataMember(Name="next_agent_id", EmitDefaultValue=false)]
        public string NextAgentId { get; set; }

        /// <summary>
        /// Gets or Sets NextAgentName
        /// </summary>
        [Required]
        [DataMember(Name="next_agent_name", EmitDefaultValue=false)]
        public string NextAgentName { get; set; }

    }
}
