/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AssistantMessage 
    {
        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name="content", EmitDefaultValue=true)]
        public Content3 Content { get; set; }

        /// <summary>
        /// Gets or Sets ToolCalls
        /// </summary>
        [DataMember(Name="tool_calls", EmitDefaultValue=true)]
        public List<ToolCall> ToolCalls { get; set; }

        /// <summary>
        /// Set this to &#x60;true&#x60; when adding an assistant message as prefix to condition the model response. The role of the prefix message is to force the model to start its answer by the content of the message.
        /// </summary>
        /// <value>Set this to &#x60;true&#x60; when adding an assistant message as prefix to condition the model response. The role of the prefix message is to force the model to start its answer by the content of the message.</value>
        [DataMember(Name="prefix", EmitDefaultValue=true)]
        public bool? Prefix { get; set; } = false;


        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        
        public enum RoleEnum
        {
            
            /// <summary>
            /// Enum AssistantEnum for assistant
            /// </summary>
            [EnumMember(Value = "assistant")]
            AssistantEnum = 1
        }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name="role", EmitDefaultValue=true)]
        public RoleEnum Role { get; set; } = RoleEnum.AssistantEnum;

    }
}
