/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ClassifierTrainingParameters 
    {
        /// <summary>
        /// Gets or Sets TrainingSteps
        /// </summary>
        [DataMember(Name="training_steps", EmitDefaultValue=true)]
        public int? TrainingSteps { get; set; }

        /// <summary>
        /// Gets or Sets LearningRate
        /// </summary>
        [Range(1.0E-8, 1)]
        [DataMember(Name="learning_rate", EmitDefaultValue=true)]
        public decimal? LearningRate { get; set; } = 1.0E-4M;

        /// <summary>
        /// Gets or Sets WeightDecay
        /// </summary>
        [Range(0, 1)]
        [DataMember(Name="weight_decay", EmitDefaultValue=true)]
        public decimal? WeightDecay { get; set; }

        /// <summary>
        /// Gets or Sets WarmupFraction
        /// </summary>
        [Range(0, 1)]
        [DataMember(Name="warmup_fraction", EmitDefaultValue=true)]
        public decimal? WarmupFraction { get; set; }

        /// <summary>
        /// Gets or Sets Epochs
        /// </summary>
        [DataMember(Name="epochs", EmitDefaultValue=true)]
        public decimal? Epochs { get; set; }

        /// <summary>
        /// Gets or Sets SeqLen
        /// </summary>
        [DataMember(Name="seq_len", EmitDefaultValue=true)]
        public int? SeqLen { get; set; }

    }
}
