/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ConversationHistoryEntriesInner 
    {

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum EntryEnum for entry
            /// </summary>
            [EnumMember(Value = "entry")]
            EntryEnum = 1
        }

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; } = ObjectEnum.EntryEnum;


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum MessageInputEnum for message.input
            /// </summary>
            [EnumMember(Value = "message.input")]
            MessageInputEnum = 1,
            
            /// <summary>
            /// Enum MessageOutputEnum for message.output
            /// </summary>
            [EnumMember(Value = "message.output")]
            MessageOutputEnum = 2,
            
            /// <summary>
            /// Enum FunctionResultEnum for function.result
            /// </summary>
            [EnumMember(Value = "function.result")]
            FunctionResultEnum = 3,
            
            /// <summary>
            /// Enum FunctionCallEnum for function.call
            /// </summary>
            [EnumMember(Value = "function.call")]
            FunctionCallEnum = 4,
            
            /// <summary>
            /// Enum ToolExecutionEnum for tool.execution
            /// </summary>
            [EnumMember(Value = "tool.execution")]
            ToolExecutionEnum = 5,
            
            /// <summary>
            /// Enum AgentHandoffEnum for agent.handoff
            /// </summary>
            [EnumMember(Value = "agent.handoff")]
            AgentHandoffEnum = 6
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; } = TypeEnum.MessageInputEnum;

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public DateTimeOffset? CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [DataMember(Name="completed_at", EmitDefaultValue=true)]
        public DateTimeOffset? CompletedAt { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string? Id { get; set; }


        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        
        public enum RoleEnum
        {
            
            /// <summary>
            /// Enum AssistantEnum for assistant
            /// </summary>
            [EnumMember(Value = "assistant")]
            AssistantEnum = 1
        }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [Required]
        [DataMember(Name="role", EmitDefaultValue=true)]
        public RoleEnum Role { get; set; } = RoleEnum.AssistantEnum;

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [Required]
        [DataMember(Name="content", EmitDefaultValue=false)]
        public Content1 Content { get; set; }

        /// <summary>
        /// Gets or Sets Prefix
        /// </summary>
        [DataMember(Name="prefix", EmitDefaultValue=true)]
        public bool? Prefix { get; set; } = false;

        /// <summary>
        /// Gets or Sets AgentId
        /// </summary>
        [DataMember(Name="agent_id", EmitDefaultValue=false)]
        public string? AgentId { get; set; }

        /// <summary>
        /// Gets or Sets Model
        /// </summary>
        [DataMember(Name="model", EmitDefaultValue=false)]
        public string? Model { get; set; }

        /// <summary>
        /// Gets or Sets ToolCallId
        /// </summary>
        [Required]
        [DataMember(Name="tool_call_id", EmitDefaultValue=false)]
        public string ToolCallId { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [Required]
        [DataMember(Name="result", EmitDefaultValue=false)]
        public string Result { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=true)]
        public BuiltInConnectors Name { get; set; }

        /// <summary>
        /// Gets or Sets Arguments
        /// </summary>
        [Required]
        [DataMember(Name="arguments", EmitDefaultValue=false)]
        public string Arguments { get; set; }

        /// <summary>
        /// Gets or Sets Info
        /// </summary>
        [DataMember(Name="info", EmitDefaultValue=false)]
        public Dictionary<string, Object> Info { get; set; }

        /// <summary>
        /// Gets or Sets PreviousAgentId
        /// </summary>
        [Required]
        [DataMember(Name="previous_agent_id", EmitDefaultValue=false)]
        public string PreviousAgentId { get; set; }

        /// <summary>
        /// Gets or Sets PreviousAgentName
        /// </summary>
        [Required]
        [DataMember(Name="previous_agent_name", EmitDefaultValue=false)]
        public string PreviousAgentName { get; set; }

        /// <summary>
        /// Gets or Sets NextAgentId
        /// </summary>
        [Required]
        [DataMember(Name="next_agent_id", EmitDefaultValue=false)]
        public string NextAgentId { get; set; }

        /// <summary>
        /// Gets or Sets NextAgentName
        /// </summary>
        [Required]
        [DataMember(Name="next_agent_name", EmitDefaultValue=false)]
        public string NextAgentName { get; set; }

    }
}
