/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Retrieve all entries in a conversation.
    /// </summary>
    [DataContract]
    public partial class ConversationHistory 
    {

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum ConversationHistoryEnum for conversation.history
            /// </summary>
            [EnumMember(Value = "conversation.history")]
            ConversationHistoryEnum = 1
        }

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; } = ObjectEnum.ConversationHistoryEnum;

        /// <summary>
        /// Gets or Sets ConversationId
        /// </summary>
        [Required]
        [DataMember(Name="conversation_id", EmitDefaultValue=false)]
        public string ConversationId { get; set; }

        /// <summary>
        /// Gets or Sets Entries
        /// </summary>
        [Required]
        [DataMember(Name="entries", EmitDefaultValue=false)]
        public List<ConversationHistoryEntriesInner> Entries { get; set; }

    }
}
