/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ConversationAppendRequest 
    {
        /// <summary>
        /// Gets or Sets Inputs
        /// </summary>
        [Required]
        [DataMember(Name="inputs", EmitDefaultValue=false)]
        public ConversationInputs Inputs { get; set; }


        /// <summary>
        /// Gets or Sets Stream
        /// </summary>
        
        public enum StreamEnum
        {
            
            /// <summary>
            /// Enum FalseEnum for false
            /// </summary>
            
            FalseEnum,
        }

        /// <summary>
        /// Gets or Sets Stream
        /// </summary>
        [DataMember(Name="stream", EmitDefaultValue=true)]
        public StreamEnum Stream { get; set; } = StreamEnum.FalseEnum;

        /// <summary>
        /// Whether to store the results into our servers or not.
        /// </summary>
        /// <value>Whether to store the results into our servers or not.</value>
        [DataMember(Name="store", EmitDefaultValue=true)]
        public bool? Store { get; set; } = true;


        /// <summary>
        /// Gets or Sets HandoffExecution
        /// </summary>
        
        public enum HandoffExecutionEnum
        {
            
            /// <summary>
            /// Enum ClientEnum for client
            /// </summary>
            [EnumMember(Value = "client")]
            ClientEnum = 1,
            
            /// <summary>
            /// Enum ServerEnum for server
            /// </summary>
            [EnumMember(Value = "server")]
            ServerEnum = 2
        }

        /// <summary>
        /// Gets or Sets HandoffExecution
        /// </summary>
        [DataMember(Name="handoff_execution", EmitDefaultValue=true)]
        public HandoffExecutionEnum HandoffExecution { get; set; } = HandoffExecutionEnum.ServerEnum;

        /// <summary>
        /// Completion arguments that will be used to generate assistant responses. Can be overridden at each message request.
        /// </summary>
        /// <value>Completion arguments that will be used to generate assistant responses. Can be overridden at each message request.</value>
        [DataMember(Name="completion_args", EmitDefaultValue=false)]
        public CompletionArgs? CompletionArgs { get; set; }

    }
}
