/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Gets or Sets FTClassifierLossFunction
        /// </summary>
        
        public enum FTClassifierLossFunction
        {
            
            /// <summary>
            /// Enum SingleClassEnum for single_class
            /// </summary>
            [EnumMember(Value = "single_class")]
            SingleClassEnum = 1,
            
            /// <summary>
            /// Enum MultiClassEnum for multi_class
            /// </summary>
            [EnumMember(Value = "multi_class")]
            MultiClassEnum = 2
        }
}
