/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ModelCapabilities 
    {
        /// <summary>
        /// Gets or Sets CompletionChat
        /// </summary>
        [DataMember(Name="completion_chat", EmitDefaultValue=true)]
        public bool? CompletionChat { get; set; } = true;

        /// <summary>
        /// Gets or Sets CompletionFim
        /// </summary>
        [DataMember(Name="completion_fim", EmitDefaultValue=true)]
        public bool? CompletionFim { get; set; } = false;

        /// <summary>
        /// Gets or Sets FunctionCalling
        /// </summary>
        [DataMember(Name="function_calling", EmitDefaultValue=true)]
        public bool? FunctionCalling { get; set; } = true;

        /// <summary>
        /// Gets or Sets FineTuning
        /// </summary>
        [DataMember(Name="fine_tuning", EmitDefaultValue=true)]
        public bool? FineTuning { get; set; } = false;

        /// <summary>
        /// Gets or Sets Vision
        /// </summary>
        [DataMember(Name="vision", EmitDefaultValue=true)]
        public bool? Vision { get; set; } = false;

        /// <summary>
        /// Gets or Sets Classification
        /// </summary>
        [DataMember(Name="classification", EmitDefaultValue=true)]
        public bool? Classification { get; set; } = false;

    }
}
