/*
 * Mistral AI API
 *
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProcessingStatusOut 
    {
        /// <summary>
        /// Gets or Sets DocumentId
        /// </summary>
        [Required]
        [DataMember(Name="document_id", EmitDefaultValue=true)]
        public Guid DocumentId { get; set; }

        /// <summary>
        /// Gets or Sets ProcessingStatus
        /// </summary>
        [Required]
        [DataMember(Name="processing_status", EmitDefaultValue=false)]
        public string ProcessingStatus { get; set; }

    }
}
