/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AdminApiKeyOwner 
    {
        /// <summary>
        /// Always &#x60;user&#x60;
        /// </summary>
        /// <value>Always &#x60;user&#x60;</value>
        /* <example>user</example> */
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string? Type { get; set; }

        /// <summary>
        /// The object type, which is always organization.user
        /// </summary>
        /// <value>The object type, which is always organization.user</value>
        /* <example>organization.user</example> */
        [DataMember(Name="object", EmitDefaultValue=false)]
        public string? Object { get; set; }

        /// <summary>
        /// The identifier, which can be referenced in API endpoints
        /// </summary>
        /// <value>The identifier, which can be referenced in API endpoints</value>
        /* <example>sa_456</example> */
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string? Id { get; set; }

        /// <summary>
        /// The name of the user
        /// </summary>
        /// <value>The name of the user</value>
        /* <example>My Service Account</example> */
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string? Name { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) of when the user was created
        /// </summary>
        /// <value>The Unix timestamp (in seconds) of when the user was created</value>
        /* <example>1711471533</example> */
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public long? CreatedAt { get; set; }

        /// <summary>
        /// Always &#x60;owner&#x60;
        /// </summary>
        /// <value>Always &#x60;owner&#x60;</value>
        /* <example>owner</example> */
        [DataMember(Name="role", EmitDefaultValue=false)]
        public string? Role { get; set; }

    }
}
