/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Represents an individual Admin API key in an org.
    /// </summary>
    [DataContract]
    public partial class AdminApiKey 
    {
        /// <summary>
        /// The object type, which is always &#x60;organization.admin_api_key&#x60;
        /// </summary>
        /// <value>The object type, which is always &#x60;organization.admin_api_key&#x60;</value>
        /* <example>organization.admin_api_key</example> */
        [Required]
        [DataMember(Name="object", EmitDefaultValue=false)]
        public string Object { get; set; }

        /// <summary>
        /// The identifier, which can be referenced in API endpoints
        /// </summary>
        /// <value>The identifier, which can be referenced in API endpoints</value>
        /* <example>key_abc</example> */
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The name of the API key
        /// </summary>
        /// <value>The name of the API key</value>
        /* <example>Administration Key</example> */
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The redacted value of the API key
        /// </summary>
        /// <value>The redacted value of the API key</value>
        /* <example>sk-admin...def</example> */
        [Required]
        [DataMember(Name="redacted_value", EmitDefaultValue=false)]
        public string RedactedValue { get; set; }

        /// <summary>
        /// The value of the API key. Only shown on create.
        /// </summary>
        /// <value>The value of the API key. Only shown on create.</value>
        /* <example>sk-admin-1234abcd</example> */
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string? Value { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) of when the API key was created
        /// </summary>
        /// <value>The Unix timestamp (in seconds) of when the API key was created</value>
        /* <example>1711471533</example> */
        [Required]
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) of when the API key was last used
        /// </summary>
        /// <value>The Unix timestamp (in seconds) of when the API key was last used</value>
        /* <example>1711471534</example> */
        [Required]
        [DataMember(Name="last_used_at", EmitDefaultValue=true)]
        public long LastUsedAt { get; set; }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [Required]
        [DataMember(Name="owner", EmitDefaultValue=false)]
        public AdminApiKeyOwner Owner { get; set; }

    }
}
