/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The session in which the audit logged action was performed.
    /// </summary>
    [DataContract]
    public partial class AuditLogActorSession 
    {
        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name="user", EmitDefaultValue=false)]
        public AuditLogActorUser? User { get; set; }

        /// <summary>
        /// The IP address from which the action was performed.
        /// </summary>
        /// <value>The IP address from which the action was performed.</value>
        [DataMember(Name="ip_address", EmitDefaultValue=false)]
        public string? IpAddress { get; set; }

    }
}
