/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The user who performed the audit logged action.
    /// </summary>
    [DataContract]
    public partial class AuditLogActorUser 
    {
        /// <summary>
        /// The user id.
        /// </summary>
        /// <value>The user id.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string? Id { get; set; }

        /// <summary>
        /// The user email.
        /// </summary>
        /// <value>The user email.</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string? Email { get; set; }

    }
}
