/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// An object representing a list of chat completion messages. 
    /// </summary>
    [DataContract]
    public partial class ChatCompletionMessageList 
    {

        /// <summary>
        /// The type of this object. It is always set to \"list\". 
        /// </summary>
        /// <value>The type of this object. It is always set to \"list\". </value>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum ListEnum for list
            /// </summary>
            [EnumMember(Value = "list")]
            ListEnum = 1
        }

        /// <summary>
        /// The type of this object. It is always set to \&quot;list\&quot;. 
        /// </summary>
        /// <value>The type of this object. It is always set to \&quot;list\&quot;. </value>
        [Required]
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; } = ObjectEnum.ListEnum;

        /// <summary>
        /// An array of chat completion message objects. 
        /// </summary>
        /// <value>An array of chat completion message objects. </value>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=false)]
        public List<ChatCompletionMessageListDataInner> Data { get; set; }

        /// <summary>
        /// The identifier of the first chat message in the data array.
        /// </summary>
        /// <value>The identifier of the first chat message in the data array.</value>
        [Required]
        [DataMember(Name="first_id", EmitDefaultValue=false)]
        public string FirstId { get; set; }

        /// <summary>
        /// The identifier of the last chat message in the data array.
        /// </summary>
        /// <value>The identifier of the last chat message in the data array.</value>
        [Required]
        [DataMember(Name="last_id", EmitDefaultValue=false)]
        public string LastId { get; set; }

        /// <summary>
        /// Indicates whether there are more chat messages available.
        /// </summary>
        /// <value>Indicates whether there are more chat messages available.</value>
        [Required]
        [DataMember(Name="has_more", EmitDefaultValue=true)]
        public bool HasMore { get; set; }

    }
}
