/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Options for streaming response. Only set this when you set &#x60;stream: true&#x60;. 
    /// </summary>
    [DataContract]
    public partial class ChatCompletionStreamOptions 
    {
        /// <summary>
        /// If set, an additional chunk will be streamed before the &#x60;data: [DONE]&#x60; message. The &#x60;usage&#x60; field on this chunk shows the token usage statistics for the entire request, and the &#x60;choices&#x60; field will always be an empty array.  All other chunks will also include a &#x60;usage&#x60; field, but with a null value. **NOTE:** If the stream is interrupted, you may not receive the final usage chunk which contains the total token usage for the request. 
        /// </summary>
        /// <value>If set, an additional chunk will be streamed before the &#x60;data: [DONE]&#x60; message. The &#x60;usage&#x60; field on this chunk shows the token usage statistics for the entire request, and the &#x60;choices&#x60; field will always be an empty array.  All other chunks will also include a &#x60;usage&#x60; field, but with a null value. **NOTE:** If the stream is interrupted, you may not receive the final usage chunk which contains the total token usage for the request. </value>
        [DataMember(Name="include_usage", EmitDefaultValue=true)]
        public bool? IncludeUsage { get; set; }

        /// <summary>
        /// When true, stream obfuscation will be enabled. Stream obfuscation adds random characters to an &#x60;obfuscation&#x60; field on streaming delta events to normalize payload sizes as a mitigation to certain side-channel attacks. These obfuscation fields are included by default, but add a small amount of overhead to the data stream. You can set &#x60;include_obfuscation&#x60; to false to optimize for bandwidth if you trust the network links between your application and the OpenAI API. 
        /// </summary>
        /// <value>When true, stream obfuscation will be enabled. Stream obfuscation adds random characters to an &#x60;obfuscation&#x60; field on streaming delta events to normalize payload sizes as a mitigation to certain side-channel attacks. These obfuscation fields are included by default, but add a small amount of overhead to the data stream. You can set &#x60;include_obfuscation&#x60; to false to optimize for bandwidth if you trust the network links between your application and the OpenAI API. </value>
        [DataMember(Name="include_obfuscation", EmitDefaultValue=true)]
        public bool? IncludeObfuscation { get; set; }

    }
}
