/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A URL citation when using web search.
    /// </summary>
    [DataContract]
    public partial class ChatCompletionResponseMessageAnnotationsInnerUrlCitation 
    {
        /// <summary>
        /// The index of the last character of the URL citation in the message.
        /// </summary>
        /// <value>The index of the last character of the URL citation in the message.</value>
        [Required]
        [DataMember(Name="end_index", EmitDefaultValue=true)]
        public int EndIndex { get; set; }

        /// <summary>
        /// The index of the first character of the URL citation in the message.
        /// </summary>
        /// <value>The index of the first character of the URL citation in the message.</value>
        [Required]
        [DataMember(Name="start_index", EmitDefaultValue=true)]
        public int StartIndex { get; set; }

        /// <summary>
        /// The URL of the web resource.
        /// </summary>
        /// <value>The URL of the web resource.</value>
        [Required]
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// The title of the web resource.
        /// </summary>
        /// <value>The title of the web resource.</value>
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

    }
}
