/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// If the audio output modality is requested, this object contains data about the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio). 
    /// </summary>
    [DataContract]
    public partial class ChatCompletionResponseMessageAudio 
    {
        /// <summary>
        /// Unique identifier for this audio response.
        /// </summary>
        /// <value>Unique identifier for this audio response.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations. 
        /// </summary>
        /// <value>The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations. </value>
        [Required]
        [DataMember(Name="expires_at", EmitDefaultValue=true)]
        public int ExpiresAt { get; set; }

        /// <summary>
        /// Base64 encoded audio bytes generated by the model, in the format specified in the request. 
        /// </summary>
        /// <value>Base64 encoded audio bytes generated by the model, in the format specified in the request. </value>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=false)]
        public string Data { get; set; }

        /// <summary>
        /// Transcript of the audio generated by the model.
        /// </summary>
        /// <value>Transcript of the audio generated by the model.</value>
        [Required]
        [DataMember(Name="transcript", EmitDefaultValue=false)]
        public string Transcript { get; set; }

    }
}
