/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The custom tool that the model called.
    /// </summary>
    [DataContract]
    public partial class ChatCompletionMessageCustomToolCallCustom 
    {
        /// <summary>
        /// The name of the custom tool to call.
        /// </summary>
        /// <value>The name of the custom tool to call.</value>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The input for the custom tool call generated by the model.
        /// </summary>
        /// <value>The input for the custom tool call generated by the model.</value>
        [Required]
        [DataMember(Name="input", EmitDefaultValue=false)]
        public string Input { get; set; }

    }
}
