/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The output of a code interpreter tool call that is a file. 
    /// </summary>
    [DataContract]
    public partial class CodeInterpreterFileOutput 
    {

        /// <summary>
        /// The type of the code interpreter file output. Always `files`. 
        /// </summary>
        /// <value>The type of the code interpreter file output. Always `files`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum FilesEnum for files
            /// </summary>
            [EnumMember(Value = "files")]
            FilesEnum = 1
        }

        /// <summary>
        /// The type of the code interpreter file output. Always &#x60;files&#x60;. 
        /// </summary>
        /// <value>The type of the code interpreter file output. Always &#x60;files&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [Required]
        [DataMember(Name="files", EmitDefaultValue=false)]
        public List<CodeInterpreterFileOutputFilesInner> Files { get; set; }

    }
}
