/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The monetary value in its associated currency.
    /// </summary>
    [DataContract]
    public partial class CostsResultAmount 
    {
        /// <summary>
        /// The numeric value of the cost.
        /// </summary>
        /// <value>The numeric value of the cost.</value>
        [DataMember(Name="value", EmitDefaultValue=true)]
        public decimal? Value { get; set; }

        /// <summary>
        /// Lowercase ISO-4217 currency e.g. \&quot;usd\&quot;
        /// </summary>
        /// <value>Lowercase ISO-4217 currency e.g. \&quot;usd\&quot;</value>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public string? Currency { get; set; }

    }
}
