/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Represents a verbose json transcription response returned by model, based on the provided input.
    /// </summary>
    [DataContract]
    public partial class CreateTranscriptionResponseVerboseJson 
    {
        /// <summary>
        /// The language of the input audio.
        /// </summary>
        /// <value>The language of the input audio.</value>
        [Required]
        [DataMember(Name="language", EmitDefaultValue=false)]
        public string Language { get; set; }

        /// <summary>
        /// The duration of the input audio.
        /// </summary>
        /// <value>The duration of the input audio.</value>
        [Required]
        [DataMember(Name="duration", EmitDefaultValue=true)]
        public decimal Duration { get; set; }

        /// <summary>
        /// The transcribed text.
        /// </summary>
        /// <value>The transcribed text.</value>
        [Required]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Extracted words and their corresponding timestamps.
        /// </summary>
        /// <value>Extracted words and their corresponding timestamps.</value>
        [DataMember(Name="words", EmitDefaultValue=false)]
        public List<TranscriptionWord> Words { get; set; }

        /// <summary>
        /// Segments of the transcribed text and their corresponding details.
        /// </summary>
        /// <value>Segments of the transcribed text and their corresponding details.</value>
        [DataMember(Name="segments", EmitDefaultValue=false)]
        public List<TranscriptionSegment> Segments { get; set; }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>
        [DataMember(Name="usage", EmitDefaultValue=false)]
        public TranscriptTextUsageDuration? Usage { get; set; }

    }
}
