/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateModerationRequestInputAnyOfInner 
    {

        /// <summary>
        /// Always `image_url`.
        /// </summary>
        /// <value>Always `image_url`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ImageUrlEnum for image_url
            /// </summary>
            [EnumMember(Value = "image_url")]
            ImageUrlEnum = 1,
            
            /// <summary>
            /// Enum TextEnum for text
            /// </summary>
            [EnumMember(Value = "text")]
            TextEnum = 2
        }

        /// <summary>
        /// Always &#x60;image_url&#x60;.
        /// </summary>
        /// <value>Always &#x60;image_url&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [Required]
        [DataMember(Name="image_url", EmitDefaultValue=false)]
        public ModerationImageURLInputImageUrl ImageUrl { get; set; }

        /// <summary>
        /// A string of text to classify.
        /// </summary>
        /// <value>A string of text to classify.</value>
        /* <example>I want to kill them</example> */
        [Required]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

    }
}
