/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Log probability information for the choice.
    /// </summary>
    [DataContract]
    public partial class CreateChatCompletionResponseChoicesInnerLogprobs 
    {
        /// <summary>
        /// A list of message content tokens with log probability information.
        /// </summary>
        /// <value>A list of message content tokens with log probability information.</value>
        [Required]
        [DataMember(Name="content", EmitDefaultValue=false)]
        public List<ChatCompletionTokenLogprob> Content { get; set; }

        /// <summary>
        /// A list of message refusal tokens with log probability information.
        /// </summary>
        /// <value>A list of message refusal tokens with log probability information.</value>
        [Required]
        [DataMember(Name="refusal", EmitDefaultValue=false)]
        public List<ChatCompletionTokenLogprob> Refusal { get; set; }

    }
}
