/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateTranscriptionResponseJsonLogprobsInner 
    {
        /// <summary>
        /// The token in the transcription.
        /// </summary>
        /// <value>The token in the transcription.</value>
        [DataMember(Name="token", EmitDefaultValue=false)]
        public string? Token { get; set; }

        /// <summary>
        /// The log probability of the token.
        /// </summary>
        /// <value>The log probability of the token.</value>
        [DataMember(Name="logprob", EmitDefaultValue=true)]
        public decimal? Logprob { get; set; }

        /// <summary>
        /// The bytes of the token.
        /// </summary>
        /// <value>The bytes of the token.</value>
        [DataMember(Name="bytes", EmitDefaultValue=false)]
        public List<decimal> Bytes { get; set; }

    }
}
