/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The image(s) to edit. Must be a supported image file or an array of images.  For &#x60;gpt-image-1&#x60;, each image should be a &#x60;png&#x60;, &#x60;webp&#x60;, or &#x60;jpg&#x60; file less  than 50MB. You can provide up to 16 images.  For &#x60;dall-e-2&#x60;, you can only provide one image, and it should be a square  &#x60;png&#x60; file less than 4MB. 
    /// </summary>
    [DataContract]
    public partial class CreateImageEditRequestImage 
    {

    }
}
