/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// One of the available [TTS models](https://platform.openai.com/docs/models#tts): &#x60;tts-1&#x60;, &#x60;tts-1-hd&#x60; or &#x60;gpt-4o-mini-tts&#x60;. 
    /// </summary>
    [DataContract]
    public partial class CreateSpeechRequestModel 
    {

    }
}
