/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateTranscriptionResponseStreamEvent 
    {

        /// <summary>
        /// The type of the event. Always `transcript.text.delta`. 
        /// </summary>
        /// <value>The type of the event. Always `transcript.text.delta`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum TranscriptTextDeltaEnum for transcript.text.delta
            /// </summary>
            [EnumMember(Value = "transcript.text.delta")]
            TranscriptTextDeltaEnum = 1,
            
            /// <summary>
            /// Enum TranscriptTextDoneEnum for transcript.text.done
            /// </summary>
            [EnumMember(Value = "transcript.text.done")]
            TranscriptTextDoneEnum = 2
        }

        /// <summary>
        /// The type of the event. Always &#x60;transcript.text.delta&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;transcript.text.delta&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The text delta that was additionally transcribed. 
        /// </summary>
        /// <value>The text delta that was additionally transcribed. </value>
        [Required]
        [DataMember(Name="delta", EmitDefaultValue=false)]
        public string Delta { get; set; }

        /// <summary>
        /// The log probabilities of the individual tokens in the transcription. Only included if you [create a transcription](https://platform.openai.com/docs/api-reference/audio/create-transcription) with the &#x60;include[]&#x60; parameter set to &#x60;logprobs&#x60;. 
        /// </summary>
        /// <value>The log probabilities of the individual tokens in the transcription. Only included if you [create a transcription](https://platform.openai.com/docs/api-reference/audio/create-transcription) with the &#x60;include[]&#x60; parameter set to &#x60;logprobs&#x60;. </value>
        [DataMember(Name="logprobs", EmitDefaultValue=false)]
        public List<TranscriptTextDeltaEventLogprobsInner> Logprobs { get; set; }

        /// <summary>
        /// The text that was transcribed. 
        /// </summary>
        /// <value>The text that was transcribed. </value>
        [Required]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>
        [DataMember(Name="usage", EmitDefaultValue=false)]
        public TranscriptTextUsageTokens? Usage { get; set; }

    }
}
