/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateEvalResponsesRunDataSourceSamplingParams 
    {
        /// <summary>
        /// A higher temperature increases randomness in the outputs.
        /// </summary>
        /// <value>A higher temperature increases randomness in the outputs.</value>
        [DataMember(Name="temperature", EmitDefaultValue=true)]
        public decimal? Temperature { get; set; } = 1M;

        /// <summary>
        /// The maximum number of tokens in the generated output.
        /// </summary>
        /// <value>The maximum number of tokens in the generated output.</value>
        [DataMember(Name="max_completion_tokens", EmitDefaultValue=true)]
        public int? MaxCompletionTokens { get; set; }

        /// <summary>
        /// An alternative to temperature for nucleus sampling; 1.0 includes all tokens.
        /// </summary>
        /// <value>An alternative to temperature for nucleus sampling; 1.0 includes all tokens.</value>
        [DataMember(Name="top_p", EmitDefaultValue=true)]
        public decimal? TopP { get; set; } = 1M;

        /// <summary>
        /// A seed value to initialize the randomness, during sampling.
        /// </summary>
        /// <value>A seed value to initialize the randomness, during sampling.</value>
        [DataMember(Name="seed", EmitDefaultValue=true)]
        public int? Seed { get; set; } = 42;

        /// <summary>
        /// An array of tools the model may call while generating a response. You can specify which tool to use by setting the &#x60;tool_choice&#x60; parameter.  The two categories of tools you can provide the model are:  - **Built-in tools**: Tools that are provided by OpenAI that extend the   model&#39;s capabilities, like [web search](https://platform.openai.com/docs/guides/tools-web-search)   or [file search](https://platform.openai.com/docs/guides/tools-file-search). Learn more about   [built-in tools](https://platform.openai.com/docs/guides/tools). - **Function calls (custom tools)**: Functions that are defined by you,   enabling the model to call your own code. Learn more about   [function calling](https://platform.openai.com/docs/guides/function-calling). 
        /// </summary>
        /// <value>An array of tools the model may call while generating a response. You can specify which tool to use by setting the &#x60;tool_choice&#x60; parameter.  The two categories of tools you can provide the model are:  - **Built-in tools**: Tools that are provided by OpenAI that extend the   model&#39;s capabilities, like [web search](https://platform.openai.com/docs/guides/tools-web-search)   or [file search](https://platform.openai.com/docs/guides/tools-file-search). Learn more about   [built-in tools](https://platform.openai.com/docs/guides/tools). - **Function calls (custom tools)**: Functions that are defined by you,   enabling the model to call your own code. Learn more about   [function calling](https://platform.openai.com/docs/guides/function-calling). </value>
        [DataMember(Name="tools", EmitDefaultValue=false)]
        public List<Tool> Tools { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public CreateEvalResponsesRunDataSourceSamplingParamsText? Text { get; set; }

    }
}
