/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DeleteFineTuningCheckpointPermissionResponse 
    {
        /// <summary>
        /// The ID of the fine-tuned model checkpoint permission that was deleted.
        /// </summary>
        /// <value>The ID of the fine-tuned model checkpoint permission that was deleted.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }


        /// <summary>
        /// The object type, which is always \"checkpoint.permission\".
        /// </summary>
        /// <value>The object type, which is always \"checkpoint.permission\".</value>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum CheckpointPermissionEnum for checkpoint.permission
            /// </summary>
            [EnumMember(Value = "checkpoint.permission")]
            CheckpointPermissionEnum = 1
        }

        /// <summary>
        /// The object type, which is always \&quot;checkpoint.permission\&quot;.
        /// </summary>
        /// <value>The object type, which is always \&quot;checkpoint.permission\&quot;.</value>
        [Required]
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; }

        /// <summary>
        /// Whether the fine-tuned model checkpoint permission was successfully deleted.
        /// </summary>
        /// <value>Whether the fine-tuned model checkpoint permission was successfully deleted.</value>
        [Required]
        [DataMember(Name="deleted", EmitDefaultValue=true)]
        public bool Deleted { get; set; }

    }
}
