/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EvalRunPerModelUsageInner 
    {
        /// <summary>
        /// The name of the model.
        /// </summary>
        /// <value>The name of the model.</value>
        [Required]
        [DataMember(Name="model_name", EmitDefaultValue=false)]
        public string ModelName { get; set; }

        /// <summary>
        /// The number of invocations.
        /// </summary>
        /// <value>The number of invocations.</value>
        [Required]
        [DataMember(Name="invocation_count", EmitDefaultValue=true)]
        public int InvocationCount { get; set; }

        /// <summary>
        /// The number of prompt tokens used.
        /// </summary>
        /// <value>The number of prompt tokens used.</value>
        [Required]
        [DataMember(Name="prompt_tokens", EmitDefaultValue=true)]
        public int PromptTokens { get; set; }

        /// <summary>
        /// The number of completion tokens generated.
        /// </summary>
        /// <value>The number of completion tokens generated.</value>
        [Required]
        [DataMember(Name="completion_tokens", EmitDefaultValue=true)]
        public int CompletionTokens { get; set; }

        /// <summary>
        /// The total number of tokens used.
        /// </summary>
        /// <value>The total number of tokens used.</value>
        [Required]
        [DataMember(Name="total_tokens", EmitDefaultValue=true)]
        public int TotalTokens { get; set; }

        /// <summary>
        /// The number of tokens retrieved from cache.
        /// </summary>
        /// <value>The number of tokens retrieved from cache.</value>
        [Required]
        [DataMember(Name="cached_tokens", EmitDefaultValue=true)]
        public int CachedTokens { get; set; }

    }
}
