/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A CustomDataSourceConfig which specifies the schema of your &#x60;item&#x60; and optionally &#x60;sample&#x60; namespaces. The response schema defines the shape of the data that will be: - Used to define your testing criteria and - What data is required when creating a run 
    /// </summary>
    [DataContract]
    public partial class EvalCustomDataSourceConfig 
    {

        /// <summary>
        /// The type of data source. Always `custom`.
        /// </summary>
        /// <value>The type of data source. Always `custom`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum CustomEnum for custom
            /// </summary>
            [EnumMember(Value = "custom")]
            CustomEnum = 1
        }

        /// <summary>
        /// The type of data source. Always &#x60;custom&#x60;.
        /// </summary>
        /// <value>The type of data source. Always &#x60;custom&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; } = TypeEnum.CustomEnum;

        /// <summary>
        /// The json schema for the run data source items. Learn how to build JSON schemas [here](https://json-schema.org/). 
        /// </summary>
        /// <value>The json schema for the run data source items. Learn how to build JSON schemas [here](https://json-schema.org/). </value>
        [Required]
        [DataMember(Name="schema", EmitDefaultValue=false)]
        public Dictionary<string, Object> Schema { get; set; }

    }
}
