/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A path to a file. 
    /// </summary>
    [DataContract]
    public partial class FilePath 
    {

        /// <summary>
        /// The type of the file path. Always `file_path`. 
        /// </summary>
        /// <value>The type of the file path. Always `file_path`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum FilePathEnum for file_path
            /// </summary>
            [EnumMember(Value = "file_path")]
            FilePathEnum = 1
        }

        /// <summary>
        /// The type of the file path. Always &#x60;file_path&#x60;. 
        /// </summary>
        /// <value>The type of the file path. Always &#x60;file_path&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The ID of the file. 
        /// </summary>
        /// <value>The ID of the file. </value>
        [Required]
        [DataMember(Name="file_id", EmitDefaultValue=false)]
        public string FileId { get; set; }

        /// <summary>
        /// The index of the file in the list of files. 
        /// </summary>
        /// <value>The index of the file in the list of files. </value>
        [Required]
        [DataMember(Name="index", EmitDefaultValue=true)]
        public int Index { get; set; }

    }
}
