/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The &#x60;checkpoint.permission&#x60; object represents a permission for a fine-tuned model checkpoint. 
    /// </summary>
    [DataContract]
    public partial class FineTuningCheckpointPermission 
    {
        /// <summary>
        /// The permission identifier, which can be referenced in the API endpoints.
        /// </summary>
        /// <value>The permission identifier, which can be referenced in the API endpoints.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) for when the permission was created.
        /// </summary>
        /// <value>The Unix timestamp (in seconds) for when the permission was created.</value>
        [Required]
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public int CreatedAt { get; set; }

        /// <summary>
        /// The project identifier that the permission is for.
        /// </summary>
        /// <value>The project identifier that the permission is for.</value>
        [Required]
        [DataMember(Name="project_id", EmitDefaultValue=false)]
        public string ProjectId { get; set; }


        /// <summary>
        /// The object type, which is always \"checkpoint.permission\".
        /// </summary>
        /// <value>The object type, which is always \"checkpoint.permission\".</value>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum CheckpointPermissionEnum for checkpoint.permission
            /// </summary>
            [EnumMember(Value = "checkpoint.permission")]
            CheckpointPermissionEnum = 1
        }

        /// <summary>
        /// The object type, which is always \&quot;checkpoint.permission\&quot;.
        /// </summary>
        /// <value>The object type, which is always \&quot;checkpoint.permission\&quot;.</value>
        [Required]
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; }

    }
}
