/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The &#x60;fine_tuning.job.checkpoint&#x60; object represents a model checkpoint for a fine-tuning job that is ready to use. 
    /// </summary>
    [DataContract]
    public partial class FineTuningJobCheckpoint 
    {
        /// <summary>
        /// The checkpoint identifier, which can be referenced in the API endpoints.
        /// </summary>
        /// <value>The checkpoint identifier, which can be referenced in the API endpoints.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) for when the checkpoint was created.
        /// </summary>
        /// <value>The Unix timestamp (in seconds) for when the checkpoint was created.</value>
        [Required]
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public int CreatedAt { get; set; }

        /// <summary>
        /// The name of the fine-tuned checkpoint model that is created.
        /// </summary>
        /// <value>The name of the fine-tuned checkpoint model that is created.</value>
        [Required]
        [DataMember(Name="fine_tuned_model_checkpoint", EmitDefaultValue=false)]
        public string FineTunedModelCheckpoint { get; set; }

        /// <summary>
        /// The step number that the checkpoint was created at.
        /// </summary>
        /// <value>The step number that the checkpoint was created at.</value>
        [Required]
        [DataMember(Name="step_number", EmitDefaultValue=true)]
        public int StepNumber { get; set; }

        /// <summary>
        /// Gets or Sets Metrics
        /// </summary>
        [Required]
        [DataMember(Name="metrics", EmitDefaultValue=false)]
        public FineTuningJobCheckpointMetrics Metrics { get; set; }

        /// <summary>
        /// The name of the fine-tuning job that this checkpoint was created from.
        /// </summary>
        /// <value>The name of the fine-tuning job that this checkpoint was created from.</value>
        [Required]
        [DataMember(Name="fine_tuning_job_id", EmitDefaultValue=false)]
        public string FineTuningJobId { get; set; }


        /// <summary>
        /// The object type, which is always \"fine_tuning.job.checkpoint\".
        /// </summary>
        /// <value>The object type, which is always \"fine_tuning.job.checkpoint\".</value>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum FineTuningJobCheckpointEnum for fine_tuning.job.checkpoint
            /// </summary>
            [EnumMember(Value = "fine_tuning.job.checkpoint")]
            FineTuningJobCheckpointEnum = 1
        }

        /// <summary>
        /// The object type, which is always \&quot;fine_tuning.job.checkpoint\&quot;.
        /// </summary>
        /// <value>The object type, which is always \&quot;fine_tuning.job.checkpoint\&quot;.</value>
        [Required]
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; }

    }
}
