/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// For &#x60;gpt-image-1&#x60; only, the token usage information for the image generation. 
    /// </summary>
    [DataContract]
    public partial class ImagesUsage 
    {
        /// <summary>
        /// The total number of tokens (images and text) used for the image generation. 
        /// </summary>
        /// <value>The total number of tokens (images and text) used for the image generation. </value>
        [Required]
        [DataMember(Name="total_tokens", EmitDefaultValue=true)]
        public int TotalTokens { get; set; }

        /// <summary>
        /// The number of tokens (images and text) in the input prompt.
        /// </summary>
        /// <value>The number of tokens (images and text) in the input prompt.</value>
        [Required]
        [DataMember(Name="input_tokens", EmitDefaultValue=true)]
        public int InputTokens { get; set; }

        /// <summary>
        /// The number of image tokens in the output image.
        /// </summary>
        /// <value>The number of image tokens in the output image.</value>
        [Required]
        [DataMember(Name="output_tokens", EmitDefaultValue=true)]
        public int OutputTokens { get; set; }

        /// <summary>
        /// Gets or Sets InputTokensDetails
        /// </summary>
        [Required]
        [DataMember(Name="input_tokens_details", EmitDefaultValue=false)]
        public ImagesUsageInputTokensDetails InputTokensDetails { get; set; }

    }
}
