/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
        /// <summary>
        /// Specify additional output data to include in the model response. Currently supported values are: - `code_interpreter_call.outputs`: Includes the outputs of python code execution   in code interpreter tool call items. - `computer_call_output.output.image_url`: Include image urls from the computer call output. - `file_search_call.results`: Include the search results of   the file search tool call. - `message.input_image.image_url`: Include image urls from the input message. - `message.output_text.logprobs`: Include logprobs with assistant messages. - `reasoning.encrypted_content`: Includes an encrypted version of reasoning   tokens in reasoning item outputs. This enables reasoning items to be used in   multi-turn conversations when using the Responses API statelessly (like   when the `store` parameter is set to `false`, or when an organization is   enrolled in the zero data retention program). 
        /// </summary>
        /// <value>Specify additional output data to include in the model response. Currently supported values are: - `code_interpreter_call.outputs`: Includes the outputs of python code execution   in code interpreter tool call items. - `computer_call_output.output.image_url`: Include image urls from the computer call output. - `file_search_call.results`: Include the search results of   the file search tool call. - `message.input_image.image_url`: Include image urls from the input message. - `message.output_text.logprobs`: Include logprobs with assistant messages. - `reasoning.encrypted_content`: Includes an encrypted version of reasoning   tokens in reasoning item outputs. This enables reasoning items to be used in   multi-turn conversations when using the Responses API statelessly (like   when the `store` parameter is set to `false`, or when an organization is   enrolled in the zero data retention program). </value>
        
        public enum Includable
        {
            
            /// <summary>
            /// Enum CodeInterpreterCallOutputsEnum for code_interpreter_call.outputs
            /// </summary>
            [EnumMember(Value = "code_interpreter_call.outputs")]
            CodeInterpreterCallOutputsEnum = 1,
            
            /// <summary>
            /// Enum ComputerCallOutputOutputImageUrlEnum for computer_call_output.output.image_url
            /// </summary>
            [EnumMember(Value = "computer_call_output.output.image_url")]
            ComputerCallOutputOutputImageUrlEnum = 2,
            
            /// <summary>
            /// Enum FileSearchCallResultsEnum for file_search_call.results
            /// </summary>
            [EnumMember(Value = "file_search_call.results")]
            FileSearchCallResultsEnum = 3,
            
            /// <summary>
            /// Enum MessageInputImageImageUrlEnum for message.input_image.image_url
            /// </summary>
            [EnumMember(Value = "message.input_image.image_url")]
            MessageInputImageImageUrlEnum = 4,
            
            /// <summary>
            /// Enum MessageOutputTextLogprobsEnum for message.output_text.logprobs
            /// </summary>
            [EnumMember(Value = "message.output_text.logprobs")]
            MessageOutputTextLogprobsEnum = 5,
            
            /// <summary>
            /// Enum ReasoningEncryptedContentEnum for reasoning.encrypted_content
            /// </summary>
            [EnumMember(Value = "reasoning.encrypted_content")]
            ReasoningEncryptedContentEnum = 6
        }
}
