/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// An image input to the model. Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
    /// </summary>
    [DataContract]
    public partial class InputImageContent 
    {

        /// <summary>
        /// The type of the input item. Always `input_image`.
        /// </summary>
        /// <value>The type of the input item. Always `input_image`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum InputImageEnum for input_image
            /// </summary>
            [EnumMember(Value = "input_image")]
            InputImageEnum = 1
        }

        /// <summary>
        /// The type of the input item. Always &#x60;input_image&#x60;.
        /// </summary>
        /// <value>The type of the input item. Always &#x60;input_image&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; } = TypeEnum.InputImageEnum;

        /// <summary>
        /// The URL of the image to be sent to the model. A fully qualified URL or base64 encoded image in a data URL.
        /// </summary>
        /// <value>The URL of the image to be sent to the model. A fully qualified URL or base64 encoded image in a data URL.</value>
        [DataMember(Name="image_url", EmitDefaultValue=true)]
        public string? ImageUrl { get; set; }

        /// <summary>
        /// The ID of the file to be sent to the model.
        /// </summary>
        /// <value>The ID of the file to be sent to the model.</value>
        [DataMember(Name="file_id", EmitDefaultValue=true)]
        public string? FileId { get; set; }


        /// <summary>
        /// The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`.
        /// </summary>
        /// <value>The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`.</value>
        
        public enum DetailEnum
        {
            
            /// <summary>
            /// Enum LowEnum for low
            /// </summary>
            [EnumMember(Value = "low")]
            LowEnum = 1,
            
            /// <summary>
            /// Enum HighEnum for high
            /// </summary>
            [EnumMember(Value = "high")]
            HighEnum = 2,
            
            /// <summary>
            /// Enum AutoEnum for auto
            /// </summary>
            [EnumMember(Value = "auto")]
            AutoEnum = 3
        }

        /// <summary>
        /// The detail level of the image to be sent to the model. One of &#x60;high&#x60;, &#x60;low&#x60;, or &#x60;auto&#x60;. Defaults to &#x60;auto&#x60;.
        /// </summary>
        /// <value>The detail level of the image to be sent to the model. One of &#x60;high&#x60;, &#x60;low&#x60;, or &#x60;auto&#x60;. Defaults to &#x60;auto&#x60;.</value>
        [Required]
        [DataMember(Name="detail", EmitDefaultValue=true)]
        public DetailEnum Detail { get; set; }

    }
}
