/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InviteRequest 
    {
        /// <summary>
        /// Send an email to this address
        /// </summary>
        /// <value>Send an email to this address</value>
        [Required]
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }


        /// <summary>
        /// `owner` or `reader`
        /// </summary>
        /// <value>`owner` or `reader`</value>
        
        public enum RoleEnum
        {
            
            /// <summary>
            /// Enum ReaderEnum for reader
            /// </summary>
            [EnumMember(Value = "reader")]
            ReaderEnum = 1,
            
            /// <summary>
            /// Enum OwnerEnum for owner
            /// </summary>
            [EnumMember(Value = "owner")]
            OwnerEnum = 2
        }

        /// <summary>
        /// &#x60;owner&#x60; or &#x60;reader&#x60;
        /// </summary>
        /// <value>&#x60;owner&#x60; or &#x60;reader&#x60;</value>
        [Required]
        [DataMember(Name="role", EmitDefaultValue=true)]
        public RoleEnum Role { get; set; }

        /// <summary>
        /// An array of projects to which membership is granted at the same time the org invite is accepted. If omitted, the user will be invited to the default project for compatibility with legacy behavior.
        /// </summary>
        /// <value>An array of projects to which membership is granted at the same time the org invite is accepted. If omitted, the user will be invited to the default project for compatibility with legacy behavior.</value>
        [DataMember(Name="projects", EmitDefaultValue=false)]
        public List<InviteRequestProjectsInner> Projects { get; set; }

    }
}
