/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A tool call to run a command on the local shell. 
    /// </summary>
    [DataContract]
    public partial class LocalShellToolCall 
    {

        /// <summary>
        /// The type of the local shell call. Always `local_shell_call`. 
        /// </summary>
        /// <value>The type of the local shell call. Always `local_shell_call`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum LocalShellCallEnum for local_shell_call
            /// </summary>
            [EnumMember(Value = "local_shell_call")]
            LocalShellCallEnum = 1
        }

        /// <summary>
        /// The type of the local shell call. Always &#x60;local_shell_call&#x60;. 
        /// </summary>
        /// <value>The type of the local shell call. Always &#x60;local_shell_call&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The unique ID of the local shell call. 
        /// </summary>
        /// <value>The unique ID of the local shell call. </value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The unique ID of the local shell tool call generated by the model. 
        /// </summary>
        /// <value>The unique ID of the local shell tool call generated by the model. </value>
        [Required]
        [DataMember(Name="call_id", EmitDefaultValue=false)]
        public string CallId { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [Required]
        [DataMember(Name="action", EmitDefaultValue=false)]
        public LocalShellExecAction Action { get; set; }


        /// <summary>
        /// The status of the local shell call. 
        /// </summary>
        /// <value>The status of the local shell call. </value>
        
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum InProgressEnum for in_progress
            /// </summary>
            [EnumMember(Value = "in_progress")]
            InProgressEnum = 1,
            
            /// <summary>
            /// Enum CompletedEnum for completed
            /// </summary>
            [EnumMember(Value = "completed")]
            CompletedEnum = 2,
            
            /// <summary>
            /// Enum IncompleteEnum for incomplete
            /// </summary>
            [EnumMember(Value = "incomplete")]
            IncompleteEnum = 3
        }

        /// <summary>
        /// The status of the local shell call. 
        /// </summary>
        /// <value>The status of the local shell call. </value>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public StatusEnum Status { get; set; }

    }
}
