/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The output of a local shell tool call. 
    /// </summary>
    [DataContract]
    public partial class LocalShellToolCallOutput 
    {

        /// <summary>
        /// The type of the local shell tool call output. Always `local_shell_call_output`. 
        /// </summary>
        /// <value>The type of the local shell tool call output. Always `local_shell_call_output`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum LocalShellCallOutputEnum for local_shell_call_output
            /// </summary>
            [EnumMember(Value = "local_shell_call_output")]
            LocalShellCallOutputEnum = 1
        }

        /// <summary>
        /// The type of the local shell tool call output. Always &#x60;local_shell_call_output&#x60;. 
        /// </summary>
        /// <value>The type of the local shell tool call output. Always &#x60;local_shell_call_output&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The unique ID of the local shell tool call generated by the model. 
        /// </summary>
        /// <value>The unique ID of the local shell tool call generated by the model. </value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// A JSON string of the output of the local shell tool call. 
        /// </summary>
        /// <value>A JSON string of the output of the local shell tool call. </value>
        [Required]
        [DataMember(Name="output", EmitDefaultValue=false)]
        public string Output { get; set; }


        /// <summary>
        /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. 
        /// </summary>
        /// <value>The status of the item. One of `in_progress`, `completed`, or `incomplete`. </value>
        
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum InProgressEnum for in_progress
            /// </summary>
            [EnumMember(Value = "in_progress")]
            InProgressEnum = 1,
            
            /// <summary>
            /// Enum CompletedEnum for completed
            /// </summary>
            [EnumMember(Value = "completed")]
            CompletedEnum = 2,
            
            /// <summary>
            /// Enum IncompleteEnum for incomplete
            /// </summary>
            [EnumMember(Value = "incomplete")]
            IncompleteEnum = 3
        }

        /// <summary>
        /// The status of the item. One of &#x60;in_progress&#x60;, &#x60;completed&#x60;, or &#x60;incomplete&#x60;. 
        /// </summary>
        /// <value>The status of the item. One of &#x60;in_progress&#x60;, &#x60;completed&#x60;, or &#x60;incomplete&#x60;. </value>
        [DataMember(Name="status", EmitDefaultValue=true)]
        public StatusEnum Status { get; set; }

    }
}
