/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Specify which of the MCP server&#39;s tools require approval.
    /// </summary>
    [DataContract]
    public partial class MCPToolRequireApproval 
    {
        /// <summary>
        /// Gets or Sets Always
        /// </summary>
        [DataMember(Name="always", EmitDefaultValue=false)]
        public MCPToolApprovalFilterAlways? Always { get; set; }

        /// <summary>
        /// Gets or Sets Never
        /// </summary>
        [DataMember(Name="never", EmitDefaultValue=false)]
        public MCPToolApprovalFilterNever? Never { get; set; }

    }
}
