/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// References an image URL in the content of a message.
    /// </summary>
    [DataContract]
    public partial class MessageDeltaContentImageUrlObject 
    {
        /// <summary>
        /// The index of the content part in the message.
        /// </summary>
        /// <value>The index of the content part in the message.</value>
        [Required]
        [DataMember(Name="index", EmitDefaultValue=true)]
        public int Index { get; set; }


        /// <summary>
        /// Always `image_url`.
        /// </summary>
        /// <value>Always `image_url`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ImageUrlEnum for image_url
            /// </summary>
            [EnumMember(Value = "image_url")]
            ImageUrlEnum = 1
        }

        /// <summary>
        /// Always &#x60;image_url&#x60;.
        /// </summary>
        /// <value>Always &#x60;image_url&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name="image_url", EmitDefaultValue=false)]
        public MessageDeltaContentImageUrlObjectImageUrl? ImageUrl { get; set; }

    }
}
