/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// References an image URL in the content of a message.
    /// </summary>
    [DataContract]
    public partial class MessageContentImageUrlObject 
    {

        /// <summary>
        /// The type of the content part.
        /// </summary>
        /// <value>The type of the content part.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ImageUrlEnum for image_url
            /// </summary>
            [EnumMember(Value = "image_url")]
            ImageUrlEnum = 1
        }

        /// <summary>
        /// The type of the content part.
        /// </summary>
        /// <value>The type of the content part.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [Required]
        [DataMember(Name="image_url", EmitDefaultValue=false)]
        public MessageContentImageUrlObjectImageUrl ImageUrl { get; set; }

    }
}
