/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Occurs when a [message](https://platform.openai.com/docs/api-reference/messages/object) moves to an &#x60;in_progress&#x60; state.
    /// </summary>
    [DataContract]
    public partial class MessageStreamEventAnyOf1 
    {

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        
        public enum EventEnum
        {
            
            /// <summary>
            /// Enum ThreadMessageInProgressEnum for thread.message.in_progress
            /// </summary>
            [EnumMember(Value = "thread.message.in_progress")]
            ThreadMessageInProgressEnum = 1
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [Required]
        [DataMember(Name="event", EmitDefaultValue=true)]
        public EventEnum Event { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=false)]
        public MessageObject Data { get; set; }

    }
}
