/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MessageContent 
    {

        /// <summary>
        /// Always `image_file`.
        /// </summary>
        /// <value>Always `image_file`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ImageFileEnum for image_file
            /// </summary>
            [EnumMember(Value = "image_file")]
            ImageFileEnum = 1,
            
            /// <summary>
            /// Enum ImageUrlEnum for image_url
            /// </summary>
            [EnumMember(Value = "image_url")]
            ImageUrlEnum = 2,
            
            /// <summary>
            /// Enum TextEnum for text
            /// </summary>
            [EnumMember(Value = "text")]
            TextEnum = 3,
            
            /// <summary>
            /// Enum RefusalEnum for refusal
            /// </summary>
            [EnumMember(Value = "refusal")]
            RefusalEnum = 4
        }

        /// <summary>
        /// Always &#x60;image_file&#x60;.
        /// </summary>
        /// <value>Always &#x60;image_file&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets ImageFile
        /// </summary>
        [Required]
        [DataMember(Name="image_file", EmitDefaultValue=false)]
        public MessageContentImageFileObjectImageFile ImageFile { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [Required]
        [DataMember(Name="image_url", EmitDefaultValue=false)]
        public MessageContentImageUrlObjectImageUrl ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [Required]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public MessageContentTextObjectText Text { get; set; }

        /// <summary>
        /// Gets or Sets Refusal
        /// </summary>
        [Required]
        [DataMember(Name="refusal", EmitDefaultValue=false)]
        public string Refusal { get; set; }

    }
}
