/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Describes an OpenAI model offering that can be used with the API.
    /// </summary>
    [DataContract]
    public partial class Model 
    {
        /// <summary>
        /// The model identifier, which can be referenced in the API endpoints.
        /// </summary>
        /// <value>The model identifier, which can be referenced in the API endpoints.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) when the model was created.
        /// </summary>
        /// <value>The Unix timestamp (in seconds) when the model was created.</value>
        [Required]
        [DataMember(Name="created", EmitDefaultValue=true)]
        public int Created { get; set; }


        /// <summary>
        /// The object type, which is always \"model\".
        /// </summary>
        /// <value>The object type, which is always \"model\".</value>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum ModelEnum for model
            /// </summary>
            [EnumMember(Value = "model")]
            ModelEnum = 1
        }

        /// <summary>
        /// The object type, which is always \&quot;model\&quot;.
        /// </summary>
        /// <value>The object type, which is always \&quot;model\&quot;.</value>
        [Required]
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; }

        /// <summary>
        /// The organization that owns the model.
        /// </summary>
        /// <value>The organization that owns the model.</value>
        [Required]
        [DataMember(Name="owned_by", EmitDefaultValue=false)]
        public string OwnedBy { get; set; }

    }
}
