/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A text output from the model. 
    /// </summary>
    [DataContract]
    public partial class OutputText 
    {

        /// <summary>
        /// The type of the output text. Always `output_text`. 
        /// </summary>
        /// <value>The type of the output text. Always `output_text`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum OutputTextEnum for output_text
            /// </summary>
            [EnumMember(Value = "output_text")]
            OutputTextEnum = 1
        }

        /// <summary>
        /// The type of the output text. Always &#x60;output_text&#x60;. 
        /// </summary>
        /// <value>The type of the output text. Always &#x60;output_text&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The text output from the model. 
        /// </summary>
        /// <value>The text output from the model. </value>
        [Required]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

    }
}
