/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProjectApiKeyOwner 
    {

        /// <summary>
        /// `user` or `service_account`
        /// </summary>
        /// <value>`user` or `service_account`</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum UserEnum for user
            /// </summary>
            [EnumMember(Value = "user")]
            UserEnum = 1,
            
            /// <summary>
            /// Enum ServiceAccountEnum for service_account
            /// </summary>
            [EnumMember(Value = "service_account")]
            ServiceAccountEnum = 2
        }

        /// <summary>
        /// &#x60;user&#x60; or &#x60;service_account&#x60;
        /// </summary>
        /// <value>&#x60;user&#x60; or &#x60;service_account&#x60;</value>
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name="user", EmitDefaultValue=false)]
        public ProjectUser? User { get; set; }

        /// <summary>
        /// Gets or Sets ServiceAccount
        /// </summary>
        [DataMember(Name="service_account", EmitDefaultValue=false)]
        public ProjectServiceAccount? ServiceAccount { get; set; }

    }
}
