/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Reference to a prompt template and its variables.  [Learn more](https://platform.openai.com/docs/guides/text?api-mode&#x3D;responses#reusable-prompts). 
    /// </summary>
    [DataContract]
    public partial class Prompt 
    {
        /// <summary>
        /// The unique identifier of the prompt template to use.
        /// </summary>
        /// <value>The unique identifier of the prompt template to use.</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Optional version of the prompt template.
        /// </summary>
        /// <value>Optional version of the prompt template.</value>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string? VarVersion { get; set; }

        /// <summary>
        /// Optional map of values to substitute in for variables in your prompt. The substitution values can either be strings, or other Response input types like images or files. 
        /// </summary>
        /// <value>Optional map of values to substitute in for variables in your prompt. The substitution values can either be strings, or other Response input types like images or files. </value>
        [DataMember(Name="variables", EmitDefaultValue=false)]
        public Dictionary<string, ResponsePromptVariablesValue> Variables { get; set; }

    }
}
