/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Send this event to update the session’s default configuration. The client may send this event at any time to update any field, except for &#x60;voice&#x60;. However, note that once a session has been initialized with a particular &#x60;model&#x60;, it can’t be changed to another model using &#x60;session.update&#x60;.  When the server receives a &#x60;session.update&#x60;, it will respond with a &#x60;session.updated&#x60; event showing the full, effective configuration. Only the fields that are present are updated. To clear a field like &#x60;instructions&#x60;, pass an empty string. 
    /// </summary>
    [DataContract]
    public partial class RealtimeClientEventSessionUpdate 
    {
        /// <summary>
        /// Optional client-generated ID used to identify this event.
        /// </summary>
        /// <value>Optional client-generated ID used to identify this event.</value>
        [DataMember(Name="event_id", EmitDefaultValue=false)]
        public string? EventId { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public Object Type { get; set; }

        /// <summary>
        /// Gets or Sets Session
        /// </summary>
        [Required]
        [DataMember(Name="session", EmitDefaultValue=false)]
        public RealtimeSessionCreateRequest Session { get; set; }

    }
}
