/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ReasoningItemContentInner 
    {

        /// <summary>
        /// The type of the object. Always `reasoning_text`. 
        /// </summary>
        /// <value>The type of the object. Always `reasoning_text`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ReasoningTextEnum for reasoning_text
            /// </summary>
            [EnumMember(Value = "reasoning_text")]
            ReasoningTextEnum = 1
        }

        /// <summary>
        /// The type of the object. Always &#x60;reasoning_text&#x60;. 
        /// </summary>
        /// <value>The type of the object. Always &#x60;reasoning_text&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Reasoning text output from the model. 
        /// </summary>
        /// <value>Reasoning text output from the model. </value>
        [Required]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

    }
}
