/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A system (or developer) message inserted into the model&#39;s context.  When using along with &#x60;previous_response_id&#x60;, the instructions from a previous response will not be carried over to the next response. This makes it simple to swap out system (or developer) messages in new responses. 
    /// </summary>
    [DataContract]
    public partial class ResponseAllOfInstructions 
    {

    }
}
