/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when the model response is complete.
    /// </summary>
    [DataContract]
    public partial class ResponseCompletedEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.completed`. 
        /// </summary>
        /// <value>The type of the event. Always `response.completed`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseCompletedEnum for response.completed
            /// </summary>
            [EnumMember(Value = "response.completed")]
            ResponseCompletedEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.completed&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.completed&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Properties of the completed response. 
        /// </summary>
        /// <value>Properties of the completed response. </value>
        [Required]
        [DataMember(Name="response", EmitDefaultValue=false)]
        public Response Response { get; set; }

        /// <summary>
        /// The sequence number for this event.
        /// </summary>
        /// <value>The sequence number for this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
