/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A detailed breakdown of the input tokens.
    /// </summary>
    [DataContract]
    public partial class ResponseUsageInputTokensDetails 
    {
        /// <summary>
        /// The number of tokens that were retrieved from the cache.  [More on prompt caching](https://platform.openai.com/docs/guides/prompt-caching). 
        /// </summary>
        /// <value>The number of tokens that were retrieved from the cache.  [More on prompt caching](https://platform.openai.com/docs/guides/prompt-caching). </value>
        [Required]
        [DataMember(Name="cached_tokens", EmitDefaultValue=true)]
        public int CachedTokens { get; set; }

    }
}
