/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// An event that is emitted when a response finishes as incomplete. 
    /// </summary>
    [DataContract]
    public partial class ResponseIncompleteEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.incomplete`. 
        /// </summary>
        /// <value>The type of the event. Always `response.incomplete`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseIncompleteEnum for response.incomplete
            /// </summary>
            [EnumMember(Value = "response.incomplete")]
            ResponseIncompleteEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.incomplete&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.incomplete&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The response that was incomplete. 
        /// </summary>
        /// <value>The response that was incomplete. </value>
        [Required]
        [DataMember(Name="response", EmitDefaultValue=false)]
        public Response Response { get; set; }

        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        /// <value>The sequence number of this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
