/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when the attempt to list available MCP tools has failed. 
    /// </summary>
    [DataContract]
    public partial class ResponseMCPListToolsFailedEvent 
    {

        /// <summary>
        /// The type of the event. Always 'response.mcp_list_tools.failed'.
        /// </summary>
        /// <value>The type of the event. Always 'response.mcp_list_tools.failed'.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseMcpListToolsFailedEnum for response.mcp_list_tools.failed
            /// </summary>
            [EnumMember(Value = "response.mcp_list_tools.failed")]
            ResponseMcpListToolsFailedEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#39;response.mcp_list_tools.failed&#39;.
        /// </summary>
        /// <value>The type of the event. Always &#39;response.mcp_list_tools.failed&#39;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The ID of the MCP tool call item that failed.
        /// </summary>
        /// <value>The ID of the MCP tool call item that failed.</value>
        [Required]
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public string ItemId { get; set; }

        /// <summary>
        /// The index of the output item that failed.
        /// </summary>
        /// <value>The index of the output item that failed.</value>
        [Required]
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int OutputIndex { get; set; }

        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        /// <value>The sequence number of this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
