/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when a response is queued and waiting to be processed. 
    /// </summary>
    [DataContract]
    public partial class ResponseQueuedEvent 
    {

        /// <summary>
        /// The type of the event. Always 'response.queued'.
        /// </summary>
        /// <value>The type of the event. Always 'response.queued'.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseQueuedEnum for response.queued
            /// </summary>
            [EnumMember(Value = "response.queued")]
            ResponseQueuedEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#39;response.queued&#39;.
        /// </summary>
        /// <value>The type of the event. Always &#39;response.queued&#39;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The full response object that is queued.
        /// </summary>
        /// <value>The full response object that is queued.</value>
        [Required]
        [DataMember(Name="response", EmitDefaultValue=false)]
        public Response Response { get; set; }

        /// <summary>
        /// The sequence number for this event.
        /// </summary>
        /// <value>The sequence number for this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
