/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A logprob is the logarithmic probability that the model assigns to producing  a particular token at a given position in the sequence. Less-negative (higher)  logprob values indicate greater model confidence in that token choice. 
    /// </summary>
    [DataContract]
    public partial class ResponseLogProb 
    {
        /// <summary>
        /// A possible text token.
        /// </summary>
        /// <value>A possible text token.</value>
        [Required]
        [DataMember(Name="token", EmitDefaultValue=false)]
        public string Token { get; set; }

        /// <summary>
        /// The log probability of this token. 
        /// </summary>
        /// <value>The log probability of this token. </value>
        [Required]
        [DataMember(Name="logprob", EmitDefaultValue=true)]
        public decimal Logprob { get; set; }

        /// <summary>
        /// The log probability of the top 20 most likely tokens. 
        /// </summary>
        /// <value>The log probability of the top 20 most likely tokens. </value>
        [DataMember(Name="top_logprobs", EmitDefaultValue=false)]
        public List<ResponseLogProbTopLogprobsInner> TopLogprobs { get; set; }

    }
}
