/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when an MCP  tool call has completed successfully. 
    /// </summary>
    [DataContract]
    public partial class ResponseMCPCallCompletedEvent 
    {

        /// <summary>
        /// The type of the event. Always 'response.mcp_call.completed'.
        /// </summary>
        /// <value>The type of the event. Always 'response.mcp_call.completed'.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseMcpCallCompletedEnum for response.mcp_call.completed
            /// </summary>
            [EnumMember(Value = "response.mcp_call.completed")]
            ResponseMcpCallCompletedEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#39;response.mcp_call.completed&#39;.
        /// </summary>
        /// <value>The type of the event. Always &#39;response.mcp_call.completed&#39;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The ID of the MCP tool call item that completed.
        /// </summary>
        /// <value>The ID of the MCP tool call item that completed.</value>
        [Required]
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public string ItemId { get; set; }

        /// <summary>
        /// The index of the output item that completed.
        /// </summary>
        /// <value>The index of the output item that completed.</value>
        [Required]
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int OutputIndex { get; set; }

        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        /// <value>The sequence number of this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
