/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A detailed breakdown of the output tokens.
    /// </summary>
    [DataContract]
    public partial class ResponseUsageOutputTokensDetails 
    {
        /// <summary>
        /// The number of reasoning tokens.
        /// </summary>
        /// <value>The number of reasoning tokens.</value>
        [Required]
        [DataMember(Name="reasoning_tokens", EmitDefaultValue=true)]
        public int ReasoningTokens { get; set; }

    }
}
