/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when a delta is added to a reasoning text.
    /// </summary>
    [DataContract]
    public partial class ResponseReasoningTextDeltaEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.reasoning_text.delta`. 
        /// </summary>
        /// <value>The type of the event. Always `response.reasoning_text.delta`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseReasoningTextDeltaEnum for response.reasoning_text.delta
            /// </summary>
            [EnumMember(Value = "response.reasoning_text.delta")]
            ResponseReasoningTextDeltaEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.reasoning_text.delta&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.reasoning_text.delta&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The ID of the item this reasoning text delta is associated with. 
        /// </summary>
        /// <value>The ID of the item this reasoning text delta is associated with. </value>
        [Required]
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public string ItemId { get; set; }

        /// <summary>
        /// The index of the output item this reasoning text delta is associated with. 
        /// </summary>
        /// <value>The index of the output item this reasoning text delta is associated with. </value>
        [Required]
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int OutputIndex { get; set; }

        /// <summary>
        /// The index of the reasoning content part this delta is associated with. 
        /// </summary>
        /// <value>The index of the reasoning content part this delta is associated with. </value>
        [Required]
        [DataMember(Name="content_index", EmitDefaultValue=true)]
        public int ContentIndex { get; set; }

        /// <summary>
        /// The text delta that was added to the reasoning content. 
        /// </summary>
        /// <value>The text delta that was added to the reasoning content. </value>
        [Required]
        [DataMember(Name="delta", EmitDefaultValue=false)]
        public string Delta { get; set; }

        /// <summary>
        /// The sequence number of this event. 
        /// </summary>
        /// <value>The sequence number of this event. </value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
