/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Details about why the response is incomplete. 
    /// </summary>
    [DataContract]
    public partial class ResponseAllOfIncompleteDetails 
    {

        /// <summary>
        /// The reason why the response is incomplete.
        /// </summary>
        /// <value>The reason why the response is incomplete.</value>
        
        public enum ReasonEnum
        {
            
            /// <summary>
            /// Enum MaxOutputTokensEnum for max_output_tokens
            /// </summary>
            [EnumMember(Value = "max_output_tokens")]
            MaxOutputTokensEnum = 1,
            
            /// <summary>
            /// Enum ContentFilterEnum for content_filter
            /// </summary>
            [EnumMember(Value = "content_filter")]
            ContentFilterEnum = 2
        }

        /// <summary>
        /// The reason why the response is incomplete.
        /// </summary>
        /// <value>The reason why the response is incomplete.</value>
        [DataMember(Name="reason", EmitDefaultValue=true)]
        public ReasonEnum Reason { get; set; }

    }
}
