/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when a new content part is added.
    /// </summary>
    [DataContract]
    public partial class ResponseContentPartAddedEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.content_part.added`. 
        /// </summary>
        /// <value>The type of the event. Always `response.content_part.added`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseContentPartAddedEnum for response.content_part.added
            /// </summary>
            [EnumMember(Value = "response.content_part.added")]
            ResponseContentPartAddedEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.content_part.added&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.content_part.added&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The ID of the output item that the content part was added to. 
        /// </summary>
        /// <value>The ID of the output item that the content part was added to. </value>
        [Required]
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public string ItemId { get; set; }

        /// <summary>
        /// The index of the output item that the content part was added to. 
        /// </summary>
        /// <value>The index of the output item that the content part was added to. </value>
        [Required]
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int OutputIndex { get; set; }

        /// <summary>
        /// The index of the content part that was added. 
        /// </summary>
        /// <value>The index of the content part that was added. </value>
        [Required]
        [DataMember(Name="content_index", EmitDefaultValue=true)]
        public int ContentIndex { get; set; }

        /// <summary>
        /// The content part that was added. 
        /// </summary>
        /// <value>The content part that was added. </value>
        [Required]
        [DataMember(Name="part", EmitDefaultValue=false)]
        public OutputContent Part { get; set; }

        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        /// <value>The sequence number of this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
