/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when there is a partial transcript of audio.
    /// </summary>
    [DataContract]
    public partial class ResponseAudioTranscriptDeltaEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.audio.transcript.delta`. 
        /// </summary>
        /// <value>The type of the event. Always `response.audio.transcript.delta`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseAudioTranscriptDeltaEnum for response.audio.transcript.delta
            /// </summary>
            [EnumMember(Value = "response.audio.transcript.delta")]
            ResponseAudioTranscriptDeltaEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.audio.transcript.delta&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.audio.transcript.delta&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The partial transcript of the audio response. 
        /// </summary>
        /// <value>The partial transcript of the audio response. </value>
        [Required]
        [DataMember(Name="delta", EmitDefaultValue=false)]
        public string Delta { get; set; }

        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        /// <value>The sequence number of this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
