/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ResponseStreamEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.audio.delta`. 
        /// </summary>
        /// <value>The type of the event. Always `response.audio.delta`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseAudioDeltaEnum for response.audio.delta
            /// </summary>
            [EnumMember(Value = "response.audio.delta")]
            ResponseAudioDeltaEnum = 1,
            
            /// <summary>
            /// Enum ResponseAudioDoneEnum for response.audio.done
            /// </summary>
            [EnumMember(Value = "response.audio.done")]
            ResponseAudioDoneEnum = 2,
            
            /// <summary>
            /// Enum ResponseAudioTranscriptDeltaEnum for response.audio.transcript.delta
            /// </summary>
            [EnumMember(Value = "response.audio.transcript.delta")]
            ResponseAudioTranscriptDeltaEnum = 3,
            
            /// <summary>
            /// Enum ResponseAudioTranscriptDoneEnum for response.audio.transcript.done
            /// </summary>
            [EnumMember(Value = "response.audio.transcript.done")]
            ResponseAudioTranscriptDoneEnum = 4,
            
            /// <summary>
            /// Enum ResponseCodeInterpreterCallCodeDeltaEnum for response.code_interpreter_call_code.delta
            /// </summary>
            [EnumMember(Value = "response.code_interpreter_call_code.delta")]
            ResponseCodeInterpreterCallCodeDeltaEnum = 5,
            
            /// <summary>
            /// Enum ResponseCodeInterpreterCallCodeDoneEnum for response.code_interpreter_call_code.done
            /// </summary>
            [EnumMember(Value = "response.code_interpreter_call_code.done")]
            ResponseCodeInterpreterCallCodeDoneEnum = 6,
            
            /// <summary>
            /// Enum ResponseCodeInterpreterCallCompletedEnum for response.code_interpreter_call.completed
            /// </summary>
            [EnumMember(Value = "response.code_interpreter_call.completed")]
            ResponseCodeInterpreterCallCompletedEnum = 7,
            
            /// <summary>
            /// Enum ResponseCodeInterpreterCallInProgressEnum for response.code_interpreter_call.in_progress
            /// </summary>
            [EnumMember(Value = "response.code_interpreter_call.in_progress")]
            ResponseCodeInterpreterCallInProgressEnum = 8,
            
            /// <summary>
            /// Enum ResponseCodeInterpreterCallInterpretingEnum for response.code_interpreter_call.interpreting
            /// </summary>
            [EnumMember(Value = "response.code_interpreter_call.interpreting")]
            ResponseCodeInterpreterCallInterpretingEnum = 9,
            
            /// <summary>
            /// Enum ResponseCompletedEnum for response.completed
            /// </summary>
            [EnumMember(Value = "response.completed")]
            ResponseCompletedEnum = 10,
            
            /// <summary>
            /// Enum ResponseContentPartAddedEnum for response.content_part.added
            /// </summary>
            [EnumMember(Value = "response.content_part.added")]
            ResponseContentPartAddedEnum = 11,
            
            /// <summary>
            /// Enum ResponseContentPartDoneEnum for response.content_part.done
            /// </summary>
            [EnumMember(Value = "response.content_part.done")]
            ResponseContentPartDoneEnum = 12,
            
            /// <summary>
            /// Enum ResponseCreatedEnum for response.created
            /// </summary>
            [EnumMember(Value = "response.created")]
            ResponseCreatedEnum = 13,
            
            /// <summary>
            /// Enum ErrorEnum for error
            /// </summary>
            [EnumMember(Value = "error")]
            ErrorEnum = 14,
            
            /// <summary>
            /// Enum ResponseFileSearchCallCompletedEnum for response.file_search_call.completed
            /// </summary>
            [EnumMember(Value = "response.file_search_call.completed")]
            ResponseFileSearchCallCompletedEnum = 15,
            
            /// <summary>
            /// Enum ResponseFileSearchCallInProgressEnum for response.file_search_call.in_progress
            /// </summary>
            [EnumMember(Value = "response.file_search_call.in_progress")]
            ResponseFileSearchCallInProgressEnum = 16,
            
            /// <summary>
            /// Enum ResponseFileSearchCallSearchingEnum for response.file_search_call.searching
            /// </summary>
            [EnumMember(Value = "response.file_search_call.searching")]
            ResponseFileSearchCallSearchingEnum = 17,
            
            /// <summary>
            /// Enum ResponseFunctionCallArgumentsDeltaEnum for response.function_call_arguments.delta
            /// </summary>
            [EnumMember(Value = "response.function_call_arguments.delta")]
            ResponseFunctionCallArgumentsDeltaEnum = 18,
            
            /// <summary>
            /// Enum ResponseFunctionCallArgumentsDoneEnum for response.function_call_arguments.done
            /// </summary>
            [EnumMember(Value = "response.function_call_arguments.done")]
            ResponseFunctionCallArgumentsDoneEnum = 19,
            
            /// <summary>
            /// Enum ResponseInProgressEnum for response.in_progress
            /// </summary>
            [EnumMember(Value = "response.in_progress")]
            ResponseInProgressEnum = 20,
            
            /// <summary>
            /// Enum ResponseFailedEnum for response.failed
            /// </summary>
            [EnumMember(Value = "response.failed")]
            ResponseFailedEnum = 21,
            
            /// <summary>
            /// Enum ResponseIncompleteEnum for response.incomplete
            /// </summary>
            [EnumMember(Value = "response.incomplete")]
            ResponseIncompleteEnum = 22,
            
            /// <summary>
            /// Enum ResponseOutputItemAddedEnum for response.output_item.added
            /// </summary>
            [EnumMember(Value = "response.output_item.added")]
            ResponseOutputItemAddedEnum = 23,
            
            /// <summary>
            /// Enum ResponseOutputItemDoneEnum for response.output_item.done
            /// </summary>
            [EnumMember(Value = "response.output_item.done")]
            ResponseOutputItemDoneEnum = 24,
            
            /// <summary>
            /// Enum ResponseReasoningSummaryPartAddedEnum for response.reasoning_summary_part.added
            /// </summary>
            [EnumMember(Value = "response.reasoning_summary_part.added")]
            ResponseReasoningSummaryPartAddedEnum = 25,
            
            /// <summary>
            /// Enum ResponseReasoningSummaryPartDoneEnum for response.reasoning_summary_part.done
            /// </summary>
            [EnumMember(Value = "response.reasoning_summary_part.done")]
            ResponseReasoningSummaryPartDoneEnum = 26,
            
            /// <summary>
            /// Enum ResponseReasoningSummaryTextDeltaEnum for response.reasoning_summary_text.delta
            /// </summary>
            [EnumMember(Value = "response.reasoning_summary_text.delta")]
            ResponseReasoningSummaryTextDeltaEnum = 27,
            
            /// <summary>
            /// Enum ResponseReasoningSummaryTextDoneEnum for response.reasoning_summary_text.done
            /// </summary>
            [EnumMember(Value = "response.reasoning_summary_text.done")]
            ResponseReasoningSummaryTextDoneEnum = 28,
            
            /// <summary>
            /// Enum ResponseReasoningTextDeltaEnum for response.reasoning_text.delta
            /// </summary>
            [EnumMember(Value = "response.reasoning_text.delta")]
            ResponseReasoningTextDeltaEnum = 29,
            
            /// <summary>
            /// Enum ResponseReasoningTextDoneEnum for response.reasoning_text.done
            /// </summary>
            [EnumMember(Value = "response.reasoning_text.done")]
            ResponseReasoningTextDoneEnum = 30,
            
            /// <summary>
            /// Enum ResponseRefusalDeltaEnum for response.refusal.delta
            /// </summary>
            [EnumMember(Value = "response.refusal.delta")]
            ResponseRefusalDeltaEnum = 31,
            
            /// <summary>
            /// Enum ResponseRefusalDoneEnum for response.refusal.done
            /// </summary>
            [EnumMember(Value = "response.refusal.done")]
            ResponseRefusalDoneEnum = 32,
            
            /// <summary>
            /// Enum ResponseOutputTextDeltaEnum for response.output_text.delta
            /// </summary>
            [EnumMember(Value = "response.output_text.delta")]
            ResponseOutputTextDeltaEnum = 33,
            
            /// <summary>
            /// Enum ResponseOutputTextDoneEnum for response.output_text.done
            /// </summary>
            [EnumMember(Value = "response.output_text.done")]
            ResponseOutputTextDoneEnum = 34,
            
            /// <summary>
            /// Enum ResponseWebSearchCallCompletedEnum for response.web_search_call.completed
            /// </summary>
            [EnumMember(Value = "response.web_search_call.completed")]
            ResponseWebSearchCallCompletedEnum = 35,
            
            /// <summary>
            /// Enum ResponseWebSearchCallInProgressEnum for response.web_search_call.in_progress
            /// </summary>
            [EnumMember(Value = "response.web_search_call.in_progress")]
            ResponseWebSearchCallInProgressEnum = 36,
            
            /// <summary>
            /// Enum ResponseWebSearchCallSearchingEnum for response.web_search_call.searching
            /// </summary>
            [EnumMember(Value = "response.web_search_call.searching")]
            ResponseWebSearchCallSearchingEnum = 37,
            
            /// <summary>
            /// Enum ResponseImageGenerationCallCompletedEnum for response.image_generation_call.completed
            /// </summary>
            [EnumMember(Value = "response.image_generation_call.completed")]
            ResponseImageGenerationCallCompletedEnum = 38,
            
            /// <summary>
            /// Enum ResponseImageGenerationCallGeneratingEnum for response.image_generation_call.generating
            /// </summary>
            [EnumMember(Value = "response.image_generation_call.generating")]
            ResponseImageGenerationCallGeneratingEnum = 39,
            
            /// <summary>
            /// Enum ResponseImageGenerationCallInProgressEnum for response.image_generation_call.in_progress
            /// </summary>
            [EnumMember(Value = "response.image_generation_call.in_progress")]
            ResponseImageGenerationCallInProgressEnum = 40,
            
            /// <summary>
            /// Enum ResponseImageGenerationCallPartialImageEnum for response.image_generation_call.partial_image
            /// </summary>
            [EnumMember(Value = "response.image_generation_call.partial_image")]
            ResponseImageGenerationCallPartialImageEnum = 41,
            
            /// <summary>
            /// Enum ResponseMcpCallArgumentsDeltaEnum for response.mcp_call_arguments.delta
            /// </summary>
            [EnumMember(Value = "response.mcp_call_arguments.delta")]
            ResponseMcpCallArgumentsDeltaEnum = 42,
            
            /// <summary>
            /// Enum ResponseMcpCallArgumentsDoneEnum for response.mcp_call_arguments.done
            /// </summary>
            [EnumMember(Value = "response.mcp_call_arguments.done")]
            ResponseMcpCallArgumentsDoneEnum = 43,
            
            /// <summary>
            /// Enum ResponseMcpCallCompletedEnum for response.mcp_call.completed
            /// </summary>
            [EnumMember(Value = "response.mcp_call.completed")]
            ResponseMcpCallCompletedEnum = 44,
            
            /// <summary>
            /// Enum ResponseMcpCallFailedEnum for response.mcp_call.failed
            /// </summary>
            [EnumMember(Value = "response.mcp_call.failed")]
            ResponseMcpCallFailedEnum = 45,
            
            /// <summary>
            /// Enum ResponseMcpCallInProgressEnum for response.mcp_call.in_progress
            /// </summary>
            [EnumMember(Value = "response.mcp_call.in_progress")]
            ResponseMcpCallInProgressEnum = 46,
            
            /// <summary>
            /// Enum ResponseMcpListToolsCompletedEnum for response.mcp_list_tools.completed
            /// </summary>
            [EnumMember(Value = "response.mcp_list_tools.completed")]
            ResponseMcpListToolsCompletedEnum = 47,
            
            /// <summary>
            /// Enum ResponseMcpListToolsFailedEnum for response.mcp_list_tools.failed
            /// </summary>
            [EnumMember(Value = "response.mcp_list_tools.failed")]
            ResponseMcpListToolsFailedEnum = 48,
            
            /// <summary>
            /// Enum ResponseMcpListToolsInProgressEnum for response.mcp_list_tools.in_progress
            /// </summary>
            [EnumMember(Value = "response.mcp_list_tools.in_progress")]
            ResponseMcpListToolsInProgressEnum = 49,
            
            /// <summary>
            /// Enum ResponseOutputTextAnnotationAddedEnum for response.output_text.annotation.added
            /// </summary>
            [EnumMember(Value = "response.output_text.annotation.added")]
            ResponseOutputTextAnnotationAddedEnum = 50,
            
            /// <summary>
            /// Enum ResponseQueuedEnum for response.queued
            /// </summary>
            [EnumMember(Value = "response.queued")]
            ResponseQueuedEnum = 51,
            
            /// <summary>
            /// Enum ResponseCustomToolCallInputDeltaEnum for response.custom_tool_call_input.delta
            /// </summary>
            [EnumMember(Value = "response.custom_tool_call_input.delta")]
            ResponseCustomToolCallInputDeltaEnum = 52,
            
            /// <summary>
            /// Enum ResponseCustomToolCallInputDoneEnum for response.custom_tool_call_input.done
            /// </summary>
            [EnumMember(Value = "response.custom_tool_call_input.done")]
            ResponseCustomToolCallInputDoneEnum = 53
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.audio.delta&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.audio.delta&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        /// <value>The sequence number of this event.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

        /// <summary>
        /// The incremental input data (delta) for the custom tool call.
        /// </summary>
        /// <value>The incremental input data (delta) for the custom tool call.</value>
        [Required]
        [DataMember(Name="delta", EmitDefaultValue=false)]
        public string Delta { get; set; }

        /// <summary>
        /// The index of the output this event applies to.
        /// </summary>
        /// <value>The index of the output this event applies to.</value>
        [Required]
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int OutputIndex { get; set; }

        /// <summary>
        /// Unique identifier for the API item associated with this event.
        /// </summary>
        /// <value>Unique identifier for the API item associated with this event.</value>
        [Required]
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public string ItemId { get; set; }

        /// <summary>
        /// The error code. 
        /// </summary>
        /// <value>The error code. </value>
        [Required]
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// The full response object that is queued.
        /// </summary>
        /// <value>The full response object that is queued.</value>
        [Required]
        [DataMember(Name="response", EmitDefaultValue=false)]
        public Response Response { get; set; }

        /// <summary>
        /// The index of the content part within the output item.
        /// </summary>
        /// <value>The index of the content part within the output item.</value>
        [Required]
        [DataMember(Name="content_index", EmitDefaultValue=true)]
        public int ContentIndex { get; set; }

        /// <summary>
        /// Gets or Sets Part
        /// </summary>
        [Required]
        [DataMember(Name="part", EmitDefaultValue=false)]
        public ResponseReasoningSummaryPartDoneEventPart Part { get; set; }

        /// <summary>
        /// The error message. 
        /// </summary>
        /// <value>The error message. </value>
        [Required]
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// The error parameter. 
        /// </summary>
        /// <value>The error parameter. </value>
        [Required]
        [DataMember(Name="param", EmitDefaultValue=false)]
        public string Param { get; set; }

        /// <summary>
        /// A JSON string containing the finalized arguments for the MCP tool call. 
        /// </summary>
        /// <value>A JSON string containing the finalized arguments for the MCP tool call. </value>
        [Required]
        [DataMember(Name="arguments", EmitDefaultValue=false)]
        public string Arguments { get; set; }

        /// <summary>
        /// The output item that was marked done. 
        /// </summary>
        /// <value>The output item that was marked done. </value>
        [Required]
        [DataMember(Name="item", EmitDefaultValue=false)]
        public OutputItem Item { get; set; }

        /// <summary>
        /// The index of the summary part within the reasoning summary. 
        /// </summary>
        /// <value>The index of the summary part within the reasoning summary. </value>
        [Required]
        [DataMember(Name="summary_index", EmitDefaultValue=true)]
        public int SummaryIndex { get; set; }

        /// <summary>
        /// The text content that is finalized. 
        /// </summary>
        /// <value>The text content that is finalized. </value>
        [Required]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// The refusal text that is finalized. 
        /// </summary>
        /// <value>The refusal text that is finalized. </value>
        [Required]
        [DataMember(Name="refusal", EmitDefaultValue=false)]
        public string Refusal { get; set; }

        /// <summary>
        /// The log probabilities of the tokens in the delta. 
        /// </summary>
        /// <value>The log probabilities of the tokens in the delta. </value>
        [Required]
        [DataMember(Name="logprobs", EmitDefaultValue=false)]
        public List<ResponseLogProb> Logprobs { get; set; }

        /// <summary>
        /// 0-based index for the partial image (backend is 1-based, but this is 0-based for the user).
        /// </summary>
        /// <value>0-based index for the partial image (backend is 1-based, but this is 0-based for the user).</value>
        [Required]
        [DataMember(Name="partial_image_index", EmitDefaultValue=true)]
        public int PartialImageIndex { get; set; }

        /// <summary>
        /// Base64-encoded partial image data, suitable for rendering as an image.
        /// </summary>
        /// <value>Base64-encoded partial image data, suitable for rendering as an image.</value>
        [Required]
        [DataMember(Name="partial_image_b64", EmitDefaultValue=false)]
        public string PartialImageB64 { get; set; }

        /// <summary>
        /// The index of the annotation within the content part.
        /// </summary>
        /// <value>The index of the annotation within the content part.</value>
        [Required]
        [DataMember(Name="annotation_index", EmitDefaultValue=true)]
        public int AnnotationIndex { get; set; }

        /// <summary>
        /// The annotation object being added. (See annotation schema for details.)
        /// </summary>
        /// <value>The annotation object being added. (See annotation schema for details.)</value>
        [Required]
        [DataMember(Name="annotation", EmitDefaultValue=false)]
        public Object Annotation { get; set; }

        /// <summary>
        /// The complete input data for the custom tool call.
        /// </summary>
        /// <value>The complete input data for the custom tool call.</value>
        [Required]
        [DataMember(Name="input", EmitDefaultValue=false)]
        public string Input { get; set; }

    }
}
