/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when a new output item is added.
    /// </summary>
    [DataContract]
    public partial class ResponseOutputItemAddedEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.output_item.added`. 
        /// </summary>
        /// <value>The type of the event. Always `response.output_item.added`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseOutputItemAddedEnum for response.output_item.added
            /// </summary>
            [EnumMember(Value = "response.output_item.added")]
            ResponseOutputItemAddedEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.output_item.added&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.output_item.added&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The index of the output item that was added. 
        /// </summary>
        /// <value>The index of the output item that was added. </value>
        [Required]
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int OutputIndex { get; set; }

        /// <summary>
        /// The sequence number of this event. 
        /// </summary>
        /// <value>The sequence number of this event. </value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

        /// <summary>
        /// The output item that was added. 
        /// </summary>
        /// <value>The output item that was added. </value>
        [Required]
        [DataMember(Name="item", EmitDefaultValue=false)]
        public OutputItem Item { get; set; }

    }
}
