/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Emitted when a web search call is executing.
    /// </summary>
    [DataContract]
    public partial class ResponseWebSearchCallSearchingEvent 
    {

        /// <summary>
        /// The type of the event. Always `response.web_search_call.searching`. 
        /// </summary>
        /// <value>The type of the event. Always `response.web_search_call.searching`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum ResponseWebSearchCallSearchingEnum for response.web_search_call.searching
            /// </summary>
            [EnumMember(Value = "response.web_search_call.searching")]
            ResponseWebSearchCallSearchingEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;response.web_search_call.searching&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;response.web_search_call.searching&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The index of the output item that the web search call is associated with. 
        /// </summary>
        /// <value>The index of the output item that the web search call is associated with. </value>
        [Required]
        [DataMember(Name="output_index", EmitDefaultValue=true)]
        public int OutputIndex { get; set; }

        /// <summary>
        /// Unique ID for the output item associated with the web search call. 
        /// </summary>
        /// <value>Unique ID for the output item associated with the web search call. </value>
        [Required]
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public string ItemId { get; set; }

        /// <summary>
        /// The sequence number of the web search call being processed.
        /// </summary>
        /// <value>The sequence number of the web search call being processed.</value>
        [Required]
        [DataMember(Name="sequence_number", EmitDefaultValue=true)]
        public int SequenceNumber { get; set; }

    }
}
