/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The grader used for the fine-tuning job.
    /// </summary>
    [DataContract]
    public partial class RunGraderRequestGrader 
    {

        /// <summary>
        /// The object type, which is always `string_check`.
        /// </summary>
        /// <value>The object type, which is always `string_check`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum StringCheckEnum for string_check
            /// </summary>
            [EnumMember(Value = "string_check")]
            StringCheckEnum = 1,
            
            /// <summary>
            /// Enum TextSimilarityEnum for text_similarity
            /// </summary>
            [EnumMember(Value = "text_similarity")]
            TextSimilarityEnum = 2,
            
            /// <summary>
            /// Enum PythonEnum for python
            /// </summary>
            [EnumMember(Value = "python")]
            PythonEnum = 3,
            
            /// <summary>
            /// Enum ScoreModelEnum for score_model
            /// </summary>
            [EnumMember(Value = "score_model")]
            ScoreModelEnum = 4,
            
            /// <summary>
            /// Enum MultiEnum for multi
            /// </summary>
            [EnumMember(Value = "multi")]
            MultiEnum = 5
        }

        /// <summary>
        /// The object type, which is always &#x60;string_check&#x60;.
        /// </summary>
        /// <value>The object type, which is always &#x60;string_check&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The name of the grader.
        /// </summary>
        /// <value>The name of the grader.</value>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The input text. This may include template strings.
        /// </summary>
        /// <value>The input text. This may include template strings.</value>
        [Required]
        [DataMember(Name="input", EmitDefaultValue=false)]
        public List<EvalItem> Input { get; set; }

        /// <summary>
        /// The text being graded against.
        /// </summary>
        /// <value>The text being graded against.</value>
        [Required]
        [DataMember(Name="reference", EmitDefaultValue=false)]
        public string Reference { get; set; }


        /// <summary>
        /// The string check operation to perform. One of `eq`, `ne`, `like`, or `ilike`.
        /// </summary>
        /// <value>The string check operation to perform. One of `eq`, `ne`, `like`, or `ilike`.</value>
        
        public enum OperationEnum
        {
            
            /// <summary>
            /// Enum EqEnum for eq
            /// </summary>
            [EnumMember(Value = "eq")]
            EqEnum = 1,
            
            /// <summary>
            /// Enum NeEnum for ne
            /// </summary>
            [EnumMember(Value = "ne")]
            NeEnum = 2,
            
            /// <summary>
            /// Enum LikeEnum for like
            /// </summary>
            [EnumMember(Value = "like")]
            LikeEnum = 3,
            
            /// <summary>
            /// Enum IlikeEnum for ilike
            /// </summary>
            [EnumMember(Value = "ilike")]
            IlikeEnum = 4
        }

        /// <summary>
        /// The string check operation to perform. One of &#x60;eq&#x60;, &#x60;ne&#x60;, &#x60;like&#x60;, or &#x60;ilike&#x60;.
        /// </summary>
        /// <value>The string check operation to perform. One of &#x60;eq&#x60;, &#x60;ne&#x60;, &#x60;like&#x60;, or &#x60;ilike&#x60;.</value>
        [Required]
        [DataMember(Name="operation", EmitDefaultValue=true)]
        public OperationEnum Operation { get; set; }


        /// <summary>
        /// The evaluation metric to use. One of `fuzzy_match`, `bleu`, `gleu`, `meteor`, `rouge_1`, `rouge_2`, `rouge_3`, `rouge_4`, `rouge_5`, or `rouge_l`.
        /// </summary>
        /// <value>The evaluation metric to use. One of `fuzzy_match`, `bleu`, `gleu`, `meteor`, `rouge_1`, `rouge_2`, `rouge_3`, `rouge_4`, `rouge_5`, or `rouge_l`.</value>
        
        public enum EvaluationMetricEnum
        {
            
            /// <summary>
            /// Enum FuzzyMatchEnum for fuzzy_match
            /// </summary>
            [EnumMember(Value = "fuzzy_match")]
            FuzzyMatchEnum = 1,
            
            /// <summary>
            /// Enum BleuEnum for bleu
            /// </summary>
            [EnumMember(Value = "bleu")]
            BleuEnum = 2,
            
            /// <summary>
            /// Enum GleuEnum for gleu
            /// </summary>
            [EnumMember(Value = "gleu")]
            GleuEnum = 3,
            
            /// <summary>
            /// Enum MeteorEnum for meteor
            /// </summary>
            [EnumMember(Value = "meteor")]
            MeteorEnum = 4,
            
            /// <summary>
            /// Enum Rouge1Enum for rouge_1
            /// </summary>
            [EnumMember(Value = "rouge_1")]
            Rouge1Enum = 5,
            
            /// <summary>
            /// Enum Rouge2Enum for rouge_2
            /// </summary>
            [EnumMember(Value = "rouge_2")]
            Rouge2Enum = 6,
            
            /// <summary>
            /// Enum Rouge3Enum for rouge_3
            /// </summary>
            [EnumMember(Value = "rouge_3")]
            Rouge3Enum = 7,
            
            /// <summary>
            /// Enum Rouge4Enum for rouge_4
            /// </summary>
            [EnumMember(Value = "rouge_4")]
            Rouge4Enum = 8,
            
            /// <summary>
            /// Enum Rouge5Enum for rouge_5
            /// </summary>
            [EnumMember(Value = "rouge_5")]
            Rouge5Enum = 9,
            
            /// <summary>
            /// Enum RougeLEnum for rouge_l
            /// </summary>
            [EnumMember(Value = "rouge_l")]
            RougeLEnum = 10
        }

        /// <summary>
        /// The evaluation metric to use. One of &#x60;fuzzy_match&#x60;, &#x60;bleu&#x60;, &#x60;gleu&#x60;, &#x60;meteor&#x60;, &#x60;rouge_1&#x60;, &#x60;rouge_2&#x60;, &#x60;rouge_3&#x60;, &#x60;rouge_4&#x60;, &#x60;rouge_5&#x60;, or &#x60;rouge_l&#x60;.
        /// </summary>
        /// <value>The evaluation metric to use. One of &#x60;fuzzy_match&#x60;, &#x60;bleu&#x60;, &#x60;gleu&#x60;, &#x60;meteor&#x60;, &#x60;rouge_1&#x60;, &#x60;rouge_2&#x60;, &#x60;rouge_3&#x60;, &#x60;rouge_4&#x60;, &#x60;rouge_5&#x60;, or &#x60;rouge_l&#x60;.</value>
        [Required]
        [DataMember(Name="evaluation_metric", EmitDefaultValue=true)]
        public EvaluationMetricEnum EvaluationMetric { get; set; }

        /// <summary>
        /// The source code of the python script.
        /// </summary>
        /// <value>The source code of the python script.</value>
        [Required]
        [DataMember(Name="source", EmitDefaultValue=false)]
        public string Source { get; set; }

        /// <summary>
        /// The image tag to use for the python script.
        /// </summary>
        /// <value>The image tag to use for the python script.</value>
        [DataMember(Name="image_tag", EmitDefaultValue=false)]
        public string? ImageTag { get; set; }

        /// <summary>
        /// The model to use for the evaluation.
        /// </summary>
        /// <value>The model to use for the evaluation.</value>
        [Required]
        [DataMember(Name="model", EmitDefaultValue=false)]
        public string Model { get; set; }

        /// <summary>
        /// The sampling parameters for the model.
        /// </summary>
        /// <value>The sampling parameters for the model.</value>
        [DataMember(Name="sampling_params", EmitDefaultValue=false)]
        public Object? SamplingParams { get; set; }

        /// <summary>
        /// The range of the score. Defaults to &#x60;[0, 1]&#x60;.
        /// </summary>
        /// <value>The range of the score. Defaults to &#x60;[0, 1]&#x60;.</value>
        [DataMember(Name="range", EmitDefaultValue=false)]
        public List<decimal> Range { get; set; }

        /// <summary>
        /// Gets or Sets Graders
        /// </summary>
        [Required]
        [DataMember(Name="graders", EmitDefaultValue=false)]
        public GraderMultiGraders Graders { get; set; }

        /// <summary>
        /// A formula to calculate the output based on grader results.
        /// </summary>
        /// <value>A formula to calculate the output based on grader results.</value>
        [Required]
        [DataMember(Name="calculate_output", EmitDefaultValue=false)]
        public string CalculateOutput { get; set; }

    }
}
