/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RunGraderResponseMetadata 
    {
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [Required]
        [DataMember(Name="errors", EmitDefaultValue=false)]
        public RunGraderResponseMetadataErrors Errors { get; set; }

        /// <summary>
        /// Gets or Sets ExecutionTime
        /// </summary>
        [Required]
        [DataMember(Name="execution_time", EmitDefaultValue=true)]
        public decimal ExecutionTime { get; set; }

        /// <summary>
        /// Gets or Sets Scores
        /// </summary>
        [Required]
        [DataMember(Name="scores", EmitDefaultValue=false)]
        public Dictionary<string, Object> Scores { get; set; }

        /// <summary>
        /// Gets or Sets TokenUsage
        /// </summary>
        [Required]
        [DataMember(Name="token_usage", EmitDefaultValue=true)]
        public int TokenUsage { get; set; }

        /// <summary>
        /// Gets or Sets SampledModelName
        /// </summary>
        [Required]
        [DataMember(Name="sampled_model_name", EmitDefaultValue=false)]
        public string SampledModelName { get; set; }

    }
}
