/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Details on the action required to continue the run. Will be &#x60;null&#x60; if no action is required.
    /// </summary>
    [DataContract]
    public partial class RunObjectRequiredAction 
    {

        /// <summary>
        /// For now, this is always `submit_tool_outputs`.
        /// </summary>
        /// <value>For now, this is always `submit_tool_outputs`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum SubmitToolOutputsEnum for submit_tool_outputs
            /// </summary>
            [EnumMember(Value = "submit_tool_outputs")]
            SubmitToolOutputsEnum = 1
        }

        /// <summary>
        /// For now, this is always &#x60;submit_tool_outputs&#x60;.
        /// </summary>
        /// <value>For now, this is always &#x60;submit_tool_outputs&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets SubmitToolOutputs
        /// </summary>
        [Required]
        [DataMember(Name="submit_tool_outputs", EmitDefaultValue=false)]
        public RunObjectRequiredActionSubmitToolOutputs SubmitToolOutputs { get; set; }

    }
}
