/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Details of the message creation by the run step.
    /// </summary>
    [DataContract]
    public partial class RunStepDeltaStepDetailsMessageCreationObject 
    {

        /// <summary>
        /// Always `message_creation`.
        /// </summary>
        /// <value>Always `message_creation`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum MessageCreationEnum for message_creation
            /// </summary>
            [EnumMember(Value = "message_creation")]
            MessageCreationEnum = 1
        }

        /// <summary>
        /// Always &#x60;message_creation&#x60;.
        /// </summary>
        /// <value>Always &#x60;message_creation&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets MessageCreation
        /// </summary>
        [DataMember(Name="message_creation", EmitDefaultValue=false)]
        public RunStepDeltaStepDetailsMessageCreationObjectMessageCreation? MessageCreation { get; set; }

    }
}
