/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SubmitToolOutputsRunRequestToolOutputsInner 
    {
        /// <summary>
        /// The ID of the tool call in the &#x60;required_action&#x60; object within the run object the output is being submitted for.
        /// </summary>
        /// <value>The ID of the tool call in the &#x60;required_action&#x60; object within the run object the output is being submitted for.</value>
        [DataMember(Name="tool_call_id", EmitDefaultValue=false)]
        public string? ToolCallId { get; set; }

        /// <summary>
        /// The output of the tool call to be submitted to continue the run.
        /// </summary>
        /// <value>The output of the tool call to be submitted to continue the run.</value>
        [DataMember(Name="output", EmitDefaultValue=false)]
        public string? Output { get; set; }

    }
}
