/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// An object specifying the format that the model must output.  Configuring &#x60;{ \&quot;type\&quot;: \&quot;json_schema\&quot; }&#x60; enables Structured Outputs,  which ensures the model will match your supplied JSON schema. Learn more in the  [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).  The default format is &#x60;{ \&quot;type\&quot;: \&quot;text\&quot; }&#x60; with no additional options.  **Not recommended for gpt-4o and newer models:**  Setting to &#x60;{ \&quot;type\&quot;: \&quot;json_object\&quot; }&#x60; enables the older JSON mode, which ensures the message the model generates is valid JSON. Using &#x60;json_schema&#x60; is preferred for models that support it. 
    /// </summary>
    [DataContract]
    public partial class TextResponseFormatConfiguration 
    {

        /// <summary>
        /// The type of response format being defined. Always `text`.
        /// </summary>
        /// <value>The type of response format being defined. Always `text`.</value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum TextEnum for text
            /// </summary>
            [EnumMember(Value = "text")]
            TextEnum = 1,
            
            /// <summary>
            /// Enum JsonSchemaEnum for json_schema
            /// </summary>
            [EnumMember(Value = "json_schema")]
            JsonSchemaEnum = 2,
            
            /// <summary>
            /// Enum JsonObjectEnum for json_object
            /// </summary>
            [EnumMember(Value = "json_object")]
            JsonObjectEnum = 3
        }

        /// <summary>
        /// The type of response format being defined. Always &#x60;text&#x60;.
        /// </summary>
        /// <value>The type of response format being defined. Always &#x60;text&#x60;.</value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// A description of what the response format is for, used by the model to determine how to respond in the format. 
        /// </summary>
        /// <value>A description of what the response format is for, used by the model to determine how to respond in the format. </value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string? Description { get; set; }

        /// <summary>
        /// The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64. 
        /// </summary>
        /// <value>The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64. </value>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The schema for the response format, described as a JSON Schema object. Learn how to build JSON schemas [here](https://json-schema.org/). 
        /// </summary>
        /// <value>The schema for the response format, described as a JSON Schema object. Learn how to build JSON schemas [here](https://json-schema.org/). </value>
        [Required]
        [DataMember(Name="schema", EmitDefaultValue=false)]
        public Dictionary<string, Object> Schema { get; set; }

        /// <summary>
        /// Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the &#x60;schema&#x60; field. Only a subset of JSON Schema is supported when &#x60;strict&#x60; is &#x60;true&#x60;. To learn more, read the [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs). 
        /// </summary>
        /// <value>Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the &#x60;schema&#x60; field. Only a subset of JSON Schema is supported when &#x60;strict&#x60; is &#x60;true&#x60;. To learn more, read the [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs). </value>
        [DataMember(Name="strict", EmitDefaultValue=true)]
        public bool? Strict { get; set; } = false;

    }
}
