/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UsageResponse 
    {

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum PageEnum for page
            /// </summary>
            [EnumMember(Value = "page")]
            PageEnum = 1
        }

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [Required]
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=false)]
        public List<UsageTimeBucket> Data { get; set; }

        /// <summary>
        /// Gets or Sets HasMore
        /// </summary>
        [Required]
        [DataMember(Name="has_more", EmitDefaultValue=true)]
        public bool HasMore { get; set; }

        /// <summary>
        /// Gets or Sets NextPage
        /// </summary>
        [Required]
        [DataMember(Name="next_page", EmitDefaultValue=false)]
        public string NextPage { get; set; }

    }
}
