/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VectorStoreSearchResultsPage 
    {

        /// <summary>
        /// The object type, which is always `vector_store.search_results.page`
        /// </summary>
        /// <value>The object type, which is always `vector_store.search_results.page`</value>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum VectorStoreSearchResultsPageEnum for vector_store.search_results.page
            /// </summary>
            [EnumMember(Value = "vector_store.search_results.page")]
            VectorStoreSearchResultsPageEnum = 1
        }

        /// <summary>
        /// The object type, which is always &#x60;vector_store.search_results.page&#x60;
        /// </summary>
        /// <value>The object type, which is always &#x60;vector_store.search_results.page&#x60;</value>
        [Required]
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; }

        /// <summary>
        /// Gets or Sets SearchQuery
        /// </summary>
        [Required]
        [DataMember(Name="search_query", EmitDefaultValue=false)]
        public List<string> SearchQuery { get; set; }

        /// <summary>
        /// The list of search result items.
        /// </summary>
        /// <value>The list of search result items.</value>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=false)]
        public List<VectorStoreSearchResultItem> Data { get; set; }

        /// <summary>
        /// Indicates if there are more results to fetch.
        /// </summary>
        /// <value>Indicates if there are more results to fetch.</value>
        [Required]
        [DataMember(Name="has_more", EmitDefaultValue=true)]
        public bool HasMore { get; set; }

        /// <summary>
        /// The token for the next page, if any.
        /// </summary>
        /// <value>The token for the next page, if any.</value>
        [Required]
        [DataMember(Name="next_page", EmitDefaultValue=false)]
        public string NextPage { get; set; }

    }
}
