/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The expiration policy for a vector store.
    /// </summary>
    [DataContract]
    public partial class VectorStoreExpirationAfter 
    {

        /// <summary>
        /// Anchor timestamp after which the expiration policy applies. Supported anchors: `last_active_at`.
        /// </summary>
        /// <value>Anchor timestamp after which the expiration policy applies. Supported anchors: `last_active_at`.</value>
        
        public enum AnchorEnum
        {
            
            /// <summary>
            /// Enum LastActiveAtEnum for last_active_at
            /// </summary>
            [EnumMember(Value = "last_active_at")]
            LastActiveAtEnum = 1
        }

        /// <summary>
        /// Anchor timestamp after which the expiration policy applies. Supported anchors: &#x60;last_active_at&#x60;.
        /// </summary>
        /// <value>Anchor timestamp after which the expiration policy applies. Supported anchors: &#x60;last_active_at&#x60;.</value>
        [Required]
        [DataMember(Name="anchor", EmitDefaultValue=true)]
        public AnchorEnum Anchor { get; set; }

        /// <summary>
        /// The number of days after the anchor time that the vector store will expire.
        /// </summary>
        /// <value>The number of days after the anchor time that the vector store will expire.</value>
        [Required]
        [Range(1, 365)]
        [DataMember(Name="days", EmitDefaultValue=true)]
        public int Days { get; set; }

    }
}
