/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A wait action. 
    /// </summary>
    [DataContract]
    public partial class Wait 
    {

        /// <summary>
        /// Specifies the event type. For a wait action, this property is  always set to `wait`. 
        /// </summary>
        /// <value>Specifies the event type. For a wait action, this property is  always set to `wait`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum WaitEnum for wait
            /// </summary>
            [EnumMember(Value = "wait")]
            WaitEnum = 1
        }

        /// <summary>
        /// Specifies the event type. For a wait action, this property is  always set to &#x60;wait&#x60;. 
        /// </summary>
        /// <value>Specifies the event type. For a wait action, this property is  always set to &#x60;wait&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; } = TypeEnum.WaitEnum;

    }
}
