/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Sent when a fine-tuning job has failed. 
    /// </summary>
    [DataContract]
    public partial class WebhookFineTuningJobFailed 
    {
        /// <summary>
        /// The Unix timestamp (in seconds) of when the fine-tuning job failed. 
        /// </summary>
        /// <value>The Unix timestamp (in seconds) of when the fine-tuning job failed. </value>
        [Required]
        [DataMember(Name="created_at", EmitDefaultValue=true)]
        public int CreatedAt { get; set; }

        /// <summary>
        /// The unique ID of the event. 
        /// </summary>
        /// <value>The unique ID of the event. </value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=false)]
        public WebhookFineTuningJobCancelledData Data { get; set; }


        /// <summary>
        /// The object of the event. Always `event`. 
        /// </summary>
        /// <value>The object of the event. Always `event`. </value>
        
        public enum ObjectEnum
        {
            
            /// <summary>
            /// Enum EventEnum for event
            /// </summary>
            [EnumMember(Value = "event")]
            EventEnum = 1
        }

        /// <summary>
        /// The object of the event. Always &#x60;event&#x60;. 
        /// </summary>
        /// <value>The object of the event. Always &#x60;event&#x60;. </value>
        [DataMember(Name="object", EmitDefaultValue=true)]
        public ObjectEnum Object { get; set; }


        /// <summary>
        /// The type of the event. Always `fine_tuning.job.failed`. 
        /// </summary>
        /// <value>The type of the event. Always `fine_tuning.job.failed`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum FineTuningJobFailedEnum for fine_tuning.job.failed
            /// </summary>
            [EnumMember(Value = "fine_tuning.job.failed")]
            FineTuningJobFailedEnum = 1
        }

        /// <summary>
        /// The type of the event. Always &#x60;fine_tuning.job.failed&#x60;. 
        /// </summary>
        /// <value>The type of the event. Always &#x60;fine_tuning.job.failed&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

    }
}
