/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// This tool searches the web for relevant results to use in a response. Learn more about the [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode&#x3D;chat). 
    /// </summary>
    [DataContract]
    public partial class WebSearch 
    {
        /// <summary>
        /// Gets or Sets UserLocation
        /// </summary>
        [DataMember(Name="user_location", EmitDefaultValue=false)]
        public WebSearchUserLocation? UserLocation { get; set; }

        /// <summary>
        /// Gets or Sets SearchContextSize
        /// </summary>
        [DataMember(Name="search_context_size", EmitDefaultValue=true)]
        public WebSearchContextSize SearchContextSize { get; set; }

    }
}
