/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The results of a web search tool call. See the  [web search guide](https://platform.openai.com/docs/guides/tools-web-search) for more information. 
    /// </summary>
    [DataContract]
    public partial class WebSearchToolCall 
    {
        /// <summary>
        /// The unique ID of the web search tool call. 
        /// </summary>
        /// <value>The unique ID of the web search tool call. </value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }


        /// <summary>
        /// The type of the web search tool call. Always `web_search_call`. 
        /// </summary>
        /// <value>The type of the web search tool call. Always `web_search_call`. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum WebSearchCallEnum for web_search_call
            /// </summary>
            [EnumMember(Value = "web_search_call")]
            WebSearchCallEnum = 1
        }

        /// <summary>
        /// The type of the web search tool call. Always &#x60;web_search_call&#x60;. 
        /// </summary>
        /// <value>The type of the web search tool call. Always &#x60;web_search_call&#x60;. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }


        /// <summary>
        /// The status of the web search tool call. 
        /// </summary>
        /// <value>The status of the web search tool call. </value>
        
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum InProgressEnum for in_progress
            /// </summary>
            [EnumMember(Value = "in_progress")]
            InProgressEnum = 1,
            
            /// <summary>
            /// Enum SearchingEnum for searching
            /// </summary>
            [EnumMember(Value = "searching")]
            SearchingEnum = 2,
            
            /// <summary>
            /// Enum CompletedEnum for completed
            /// </summary>
            [EnumMember(Value = "completed")]
            CompletedEnum = 3,
            
            /// <summary>
            /// Enum FailedEnum for failed
            /// </summary>
            [EnumMember(Value = "failed")]
            FailedEnum = 4
        }

        /// <summary>
        /// The status of the web search tool call. 
        /// </summary>
        /// <value>The status of the web search tool call. </value>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=true)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [Required]
        [DataMember(Name="action", EmitDefaultValue=false)]
        public WebSearchToolCallAction Action { get; set; }

    }
}
