/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Action type \&quot;search\&quot; - Performs a web search query. 
    /// </summary>
    [DataContract]
    public partial class WebSearchActionSearch 
    {

        /// <summary>
        /// The action type. 
        /// </summary>
        /// <value>The action type. </value>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum SearchEnum for search
            /// </summary>
            [EnumMember(Value = "search")]
            SearchEnum = 1
        }

        /// <summary>
        /// The action type. 
        /// </summary>
        /// <value>The action type. </value>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// The search query. 
        /// </summary>
        /// <value>The search query. </value>
        [Required]
        [DataMember(Name="query", EmitDefaultValue=false)]
        public string Query { get; set; }

    }
}
