/*
 * Anthropic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BetaMessageBatchIndividualResponse 
    {
        /// <summary>
        /// Developer-provided ID created for each request in a Message Batch. Useful for matching results to requests, as results may be given out of request order.  Must be unique for each request within the Message Batch.
        /// </summary>
        /// <value>Developer-provided ID created for each request in a Message Batch. Useful for matching results to requests, as results may be given out of request order.  Must be unique for each request within the Message Batch.</value>
        [Required]
        [DataMember(Name="custom_id", EmitDefaultValue=false)]
        public string CustomId { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [Required]
        [DataMember(Name="result", EmitDefaultValue=false)]
        public BetaMessageBatchResult Result { get; set; }

    }
}
