/*
 * Anthropic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BetaBashTool20241022 
    {
        /// <summary>
        /// Gets or Sets CacheControl
        /// </summary>
        [DataMember(Name="cache_control", EmitDefaultValue=true)]
        public BetaCacheControlEphemeral CacheControl { get; set; }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum Bash20241022Enum for bash_20241022
            /// </summary>
            [EnumMember(Value = "bash_20241022")]
            Bash20241022Enum = 1
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }


        /// <summary>
        /// Name of the tool.  This is how the tool will be called by the model and in tool_use blocks.
        /// </summary>
        /// <value>Name of the tool.  This is how the tool will be called by the model and in tool_use blocks.</value>
        
        public enum NameEnum
        {
            
            /// <summary>
            /// Enum BashEnum for bash
            /// </summary>
            [EnumMember(Value = "bash")]
            BashEnum = 1
        }

        /// <summary>
        /// Name of the tool.  This is how the tool will be called by the model and in tool_use blocks.
        /// </summary>
        /// <value>Name of the tool.  This is how the tool will be called by the model and in tool_use blocks.</value>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=true)]
        public NameEnum Name { get; set; }

    }
}
