/*
 * Anthropic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BetaListResponseMessageBatch 
    {
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [Required]
        [DataMember(Name="data", EmitDefaultValue=false)]
        public List<BetaMessageBatch> Data { get; set; }

        /// <summary>
        /// Indicates if there are more results in the requested page direction.
        /// </summary>
        /// <value>Indicates if there are more results in the requested page direction.</value>
        [Required]
        [DataMember(Name="has_more", EmitDefaultValue=true)]
        public bool HasMore { get; set; }

        /// <summary>
        /// Gets or Sets FirstId
        /// </summary>
        [Required]
        [DataMember(Name="first_id", EmitDefaultValue=true)]
        public string? FirstId { get; set; }

        /// <summary>
        /// Gets or Sets LastId
        /// </summary>
        [Required]
        [DataMember(Name="last_id", EmitDefaultValue=true)]
        public string? LastId { get; set; }

    }
}
