/*
 * Anthropic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using JsonSubTypes;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    [JsonSubtypes.KnownSubType(typeof(RequestImageBlock), "image")]
    [JsonSubtypes.KnownSubType(typeof(RequestTextBlock), "text")]
    [JsonSubtypes.KnownSubType(typeof(RequestToolResultBlock), "tool_result")]
    [JsonSubtypes.KnownSubType(typeof(RequestToolUseBlock), "tool_use")]
    public partial class Block1 
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum TextEnum for text
            /// </summary>
            [EnumMember(Value = "text")]
            TextEnum = 1,
            
            /// <summary>
            /// Enum ImageEnum for image
            /// </summary>
            [EnumMember(Value = "image")]
            ImageEnum = 2,
            
            /// <summary>
            /// Enum ToolUseEnum for tool_use
            /// </summary>
            [EnumMember(Value = "tool_use")]
            ToolUseEnum = 3,
            
            /// <summary>
            /// Enum ToolResultEnum for tool_result
            /// </summary>
            [EnumMember(Value = "tool_result")]
            ToolResultEnum = 4
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [Required]
        [MinLength(1)]
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [Required]
        [DataMember(Name="source", EmitDefaultValue=false)]
        public Base64ImageSource Source { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [RegularExpression("^[a-zA-Z0-9_-]+$")]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [RegularExpression("^[a-zA-Z0-9_-]{1,64}$")]
        [StringLength(64, MinimumLength=1)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Input
        /// </summary>
        [Required]
        [DataMember(Name="input", EmitDefaultValue=false)]
        public Object Input { get; set; }

        /// <summary>
        /// Gets or Sets ToolUseId
        /// </summary>
        [Required]
        [RegularExpression("^[a-zA-Z0-9_-]+$")]
        [DataMember(Name="tool_use_id", EmitDefaultValue=false)]
        public string ToolUseId { get; set; }

        /// <summary>
        /// Gets or Sets IsError
        /// </summary>
        [DataMember(Name="is_error", EmitDefaultValue=true)]
        public bool? IsError { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name="content", EmitDefaultValue=false)]
        public Content5? Content { get; set; }

    }
}
