/*
 * Anthropic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PromptCachingBetaTool 
    {
        /// <summary>
        /// Description of what this tool does.  Tool descriptions should be as detailed as possible. The more information that the model has about what the tool is and how to use it, the better it will perform. You can use natural language descriptions to reinforce important aspects of the tool input JSON schema.
        /// </summary>
        /// <value>Description of what this tool does.  Tool descriptions should be as detailed as possible. The more information that the model has about what the tool is and how to use it, the better it will perform. You can use natural language descriptions to reinforce important aspects of the tool input JSON schema.</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string? Description { get; set; }

        /// <summary>
        /// Name of the tool.  This is how the tool will be called by the model and in tool_use blocks.
        /// </summary>
        /// <value>Name of the tool.  This is how the tool will be called by the model and in tool_use blocks.</value>
        [Required]
        [RegularExpression("^[a-zA-Z0-9_-]{1,64}$")]
        [StringLength(64, MinimumLength=1)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// [JSON schema](https://json-schema.org/) for this tool&#39;s input.  This defines the shape of the &#x60;input&#x60; that your tool accepts and that the model will produce.
        /// </summary>
        /// <value>[JSON schema](https://json-schema.org/) for this tool&#39;s input.  This defines the shape of the &#x60;input&#x60; that your tool accepts and that the model will produce.</value>
        [Required]
        [DataMember(Name="input_schema", EmitDefaultValue=false)]
        public InputSchema InputSchema { get; set; }

        /// <summary>
        /// Gets or Sets CacheControl
        /// </summary>
        [DataMember(Name="cache_control", EmitDefaultValue=true)]
        public CacheControlEphemeral CacheControl { get; set; }

    }
}
